### ISSUE TITLE
tldr in ubuntu repos

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#10138]
Running `tldr` in WSL Ubuntu 22.04.1 says 
```
Command 'tldr' not found, but can be installed with:
sudo apt install tldr     # version 0.6.4-1build6.3, or
sudo apt install tldr-py  # version 0.7.0-4
```
are these officially supported clients? should it be mentioned in the README?

**Comment by pixelcmtd** [comment]
[Our wiki](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients) has a list of officially recognized clients. The Ubuntu package [`tldr`](https://packages.ubuntu.com/kinetic/tldr) seems to be [`tldr-hs`](https://github.com/psibi/tldr-hs), a sporadically maintained, but working client. [`tldr-py`](https://packages.ubuntu.com/kinetic/tldr-py) seems to be [`tldr.py`](https://github.com/lord63/tldr.py), a client that is uncompliant, appears to be unmaintained since about 2020 and [is broken as of today](https://github.com/tldr-pages/tldr/issues/9628).
If you want to install an Ubuntu package, I'd go with `tldr`. Otherwise, you might want to have a look at [`tealdeer`](https://github.com/dbrgn/tealdeer) and [our official Python client](https://github.com/tldr-pages/tldr-python-client).

**Comment by kbdharun** [comment]
> [Our wiki](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients) has a list of officially recognized clients. The Ubuntu package [`tldr`](https://packages.ubuntu.com/kinetic/tldr) seems to be [`tldr-hs`](https://github.com/psibi/tldr-hs) (-based? see #5962), a sporadically maintained, but working client. [`tldr-py`](https://packages.ubuntu.com/kinetic/tldr-py) seems to be [`tldr.py`](https://github.com/lord63/tldr.py), a client that is uncompliant, appears to be unmaintained since about 2020 and [is broken as of today](https://github.com/tldr-pages/tldr/issues/9628).
> If you want to install an Ubuntu package, I'd go with `tldr`. Otherwise, you might want to have a look at [`tealdeer`](https://github.com/dbrgn/tealdeer) and [our official Python client](https://github.com/tldr-pages/tldr-python-client).


Regarding the python client, we need to make a release, because we updated the source there too. Similarly, the Haskell client.
