### ISSUE TITLE
Issue upon fresh install of debian (whereas was previously working)

### ISSUE THREAD

**Issue by randall-mcpherson** [tldr-pages/tldr#10207]
receive the following message upon command "tldr [command]" after fresh install
tldr: /home/user/.local/share/tldr: createDirectory: does not exist (No such file or directory)"
worked fine previously, however, upon fresh install of debian, was presented with this
when simply inputting command "tldr" the "usage" splash text is displayed
for whatever reason, it is not setting up completely

**Comment by randall-mcpherson** [comment]
after manually making the directory specified, the output for tldr becomes "no entry for ___." Can someone provide a solution?

**Comment by kbdharun** [comment]
We are aware of this issue with a third-party client. I think it should be fixed in Bookworm (Debian 12) as it ships a newer version of it.

I would suggest you use our Python client by installing it using `pip install tldr` command or if you use Homebrew you can install our C client using brew install tldr or you can install our Node client using `npm install tldr`.

**Comment by randall-mcpherson** [comment]
Greetings,

So I managed to fix the issue, but I thought I should let you know that I am using bookworm debian 12. If it helps, what I had to do was manually create the directory, and then do tldr -u. Thanks.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by randall-mcpherson** [comment]
I had yet another issue, and had to reinstall Debian (again...) and the previous workaround I used is no longer working. This time, when I tried `tldr -u` I was presented with the notice:
`tldr: /home/user/.local/share/tldr: removePathForcibly:removeDirectory: permission denied (Permission denied)`
when I try `sudo tldr -u` I am again presented with the same error, saying there is no such directory in root, and it specifies to create the directory.

**Comment by 444B** [comment]
Confirmed to still be an issue for me and has existed for roughly the last year
- happens on all new fresh installs of tldr when I run tldr --update 
- installed with apt

**Comment by kbdharun** [comment]
> Confirmed to still be an issue for me and has existed for roughly the last year
> 
> * happens on all new fresh installs of tldr when I run tldr --update
> * installed with apt

Hi, We don't package our official clients for Debian (we are open to doing it, but communication/backports could be quite an issue), you are using a community client instead.

If you installed `tldr` with Apt you no longer would be able to do it with newer versions of Debian (i.e. Sid, experimental) and also interim releases of Ubuntu (this will also reflect in the upcoming LTS release too) as the package has been marked as transitional and has been renamed to the correct tldr-hs name.

Given that https://github.com/psibi/tldr-hs hasn't been updated for more than 2 years and doesn't comply with the recent client specification I believe it might not get updated in time and would break in the near future when we remove assets from the website (we have already started publishing our assets via  GitHub releases and a client specification release would be made soon for it https://github.com/tldr-pages/tldr/milestone/3).

----

If you are on Ubuntu you can install tldr's Python client easily with `snap install tldr`, alternatively you can checkout https://github.com/tldr-pages/tldr?tab=readme-ov-file#how-do-i-use-it for more options.

----

Unfortunately we can't do anything about this issue rather than suggesting an official client so I am closing it as not planned. Regarding sites/old articles referencing this method, I will try to contact them to link to our README/add a note instead.
