### ISSUE TITLE
Customize output color

### ISSUE THREAD

**Issue by PetrusKiendys** [tldr-pages/tldr#10236]
Is there any way to customize output color?
If not, is it perhaps possible to implement something like color themes, palettes or maybe even manually configure colors in a config file?
I'm using Windows Subsystem for Linux (WSL) at the moment and the output looks terrible.
Especially the first line of every bullet list item is very difficult to read as it blends in with the background of my terminal.

See attached screenshot:
![tldr-tldr](https://github.com/tldr-pages/tldr/assets/2377215/444f8851-4e19-4029-8f3e-a51c81a2f1eb)

**Comment by kbdharun** [comment]
> I'm using Windows Subsystem for Linux (WSL)

Since you are using WSL I assume you install `tldr` using the `apt install tldr` command then it would have installed a third-party client [tldr-hs](https://github.com/psibi/tldr-hs). I would suggest using the official [Node client](https://github.com/tldr-pages/tldr-node-client) since you are on Windows, the installation can be done using the command `npm install tldr` and the instructions for customizing colour output for it is [here](https://github.com/tldr-pages/tldr-node-client#colors-under-cygwin).

If you prefer installing it inside WSL, then you can install our official [Python client](https://github.com/tldr-pages/tldr-python-client) using the command `pip install tldr`, it comes with multiple colour options out of the box while you can see by typing `tldr --help`.
