### ISSUE TITLE
Error upon updating 

### ISSUE THREAD

**Issue by matilde-t** [tldr-pages/tldr#10313]
Hi, when I try to update, now I get an error. It was working until a few weeks ago

Using Pop!OS 22.04 (based on Ubuntu)
 ```
mati@pop-os:~$ tldr -u
fatal: couldn't find remote ref master
tldr: Received ExitFailure 1 when running
Raw command: git pull origin master
Run from: /home/mati/.local/share/tldr/tldr
```

**Comment by kbdharun** [comment]
Hi, thanks for the issue. The client in question is a third-party community client called tldr-hs, this issue  is fixed in the latest 23.04 release repos but not backported to older LTS releases, we have reached out to the package maintainers.

I would suggest you switch to our Python or NodeJS (npm) [preferred] client listed in README. If you want to use a third party client from Ubuntu repos then check out `tealdeer` (which is one of the popular community clients).
