### ISSUE TITLE
add bioinformatic tools (bedtools, samtools, etc.)

### ISSUE THREAD

**Issue by mashehu** [tldr-pages/tldr#1084]
Possible sources for [bedtools](http://bedtools.readthedocs.io/en/latest/content/example-usage.html) or for [samtools](http://davetang.org/wiki/tiki-index.php?page=SAMTools).

**Comment by ewels** [comment]
There are loads of bioinformatics tools that could be nicely documented with _tldr_. @waldyrious - would it make sense to keep them separate somehow, so that they don't bloat the main package?

**Comment by waldyrious** [comment]
This is something that has to be decided on a case-by-case basis, by those familiar with the tools. There certainly is precedent for it, see git and csvkit (#702).

**Comment by waldyrious** [comment]
I might have misunderstood you. By main package do you mean tldr-pages repo? Separate page stores have been floated before by @ostera (tried to find an issue or PR reference, but I guess we chatted on Gitter rather than here). @ostera could you chime in?

**Comment by ewels** [comment]
Yes sorry, I wasn't very clear. I meant the tldr-pages repo. Could be something like the existing `common`/`linux`/`osx` type thing? Or a separate repo. I was vaguely thinking along the lines of the previously mentioned channels with conda. A nice way to collect tools of a similar nature. If you look at the list of bioinformatics software in the [bioconda conda channel](https://bioconda.github.io/) that they have then that gives you an idea for the potential number of _tldr_ entries (in a perfect world!). Though in fairness not all of these are command line tools.

**Comment by waldyrious** [comment]
Yes, we'd need to define a standard for where such pages could live (e.g. git repositories with a "pages" directory, like this one) and how existing clients could be made to point to them (adding a new registry to their internal list, rather than having the default tldr pages hardcoded.)

But until then, I don't think it's a bad idea to just add more tools to this repo, since as text files they don't really take that much space. The only issue would be tool name collisions, but hopefully those should be rare enough to be dealt with individually.

**Comment by waldyrious** [comment]
Update: samtools have now been added with the merging of #1159, great job @ewels!

I'll create a separate issue to track bedtools, rename this one and close it. If we leave it open-ended, it will never be closed...
