### ISSUE TITLE
URL's for More Information are formatted with an extra dot at the end 

### ISSUE THREAD

**Issue by BlendyDev** [tldr-pages/tldr#10989]
From what I've seen, in some common tldr pages, the url containing "More Information" has an extra "." character appended at the end. Some terminal emulators (I'm using Konsole) recognize the dot as part of the URL and when clicked, it will sometimes take you to invalid pages.
![image](https://github.com/tldr-pages/tldr/assets/63923395/6d301d25-10fd-4610-9d73-03fa6b7d482b)
![image](https://github.com/tldr-pages/tldr/assets/63923395/c80c566b-440b-49bd-b264-f4192400f595)

**Comment by kbdharun** [comment]
Hi, thanks for the issue. We recently had one other report similar to this at <https://github.com/tldr-pages/tldr/pull/10807>. It seems that regardless of the tldr client, Konsole detects the period beside the links too. I would suggest forwarding this issue to the Konsole devs to see what they think.

**Comment by BlendyDev** [comment]
I still consider this to be an issue on tldr's side, for example, a website might intentionally have a period at the end (and only work with it) and a terminal emulator considering it as part of the URL could very well be intended behaviour. Also, if adding [] around the URL is being considered, I don't know why just removing the trailing dot like in https://github.com/tldr-pages/tldr/pull/10807 isn't (imo it'd be less invasive and look almost the same to end users).

**Comment by acuteenvy** [comment]
> a terminal emulator considering it as part of the URL could very well be intended behaviour.

I tested [alacritty](https://github.com/alacritty/alacritty), [kitty](https://github.com/kovidgoyal/kitty), [wezterm](https://github.com/wez/wezterm), [qterminal](https://github.com/lxqt/qterminal), [xfce4-terminal](https://gitlab.xfce.org/apps/xfce4-terminal) and [gnome-terminal](https://gitlab.gnome.org/GNOME/gnome-terminal) - all of them don't think the dot is a part of the URL. I think it's pretty safe to say the issue is on Konsole's side.
