### ISSUE TITLE
Take care of unmaintained tldr repositories

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#1104]
There are two unmainatined repositories in tldr-pages organization:
1. [tldr_elixir_client](https://github.com/tldr-pages/tldr_elixir_client)
2. [tldr-cli](https://github.com/tldr-pages/tldr-cli)

Elixir client is basically outdated, so it should just be marked as unmaintained. tldr-cli, on the other hand, seems empty so I think it's fine to delete it.

What do you think?

**Comment by waldyrious** [comment]
I've been thinking about moving the repos [back to their original owners](https://github.com/tldr-pages/tldr/pull/386/files), so that would be my preferred outcome. I would like to finish defining the [specs for the officially sanctioned clients](https://github.com/tldr-pages/tldr/issues/1065), though, before doing any changes to the clients. Any help on that front would be appreciated! 😄 

As for tldr-cli, I'm not sure what @igorshubovych was going for with it, so before deleting the repo I'd like to hear his word.

**Comment by agnivade** [comment]
The homebrew formula repo is also redundant since its available through the core homebrew repository now. Can we delete that ?

**Comment by zdroid** [comment]
@agnivade I think we can drop that now. Also check the two repositories I've mentioned above and state your opinion on deleting them if possible. :smile:

**Comment by waldyrious** [comment]
> The homebrew formula repo is also redundant since its available through the core homebrew repository now. Can we delete that ?

I suspect so, but since it's been maintained until recently, and has a few followers/stargazers, I'd refrain from deleting itwithout @Leandros' input.

As for tldr-cli, since @igorshubovych has't reacted after over a week (and he's been active on github since my comment above), I would say it's safe to delete it.

**Comment by zdroid** [comment]
Well, tldr-cli is almost an empty repository, so it'll be harmless if we delete it.

**Comment by agnivade** [comment]
> Also check the two repositories I've mentioned above and state your opinion

Hmm .. moving the repos back to their original owners might be a bit difficult for inactive owners. For eg. now if the node client is moved to @rprieto's repo. I need to get the commit permission again and set up the repo branch permissions like I have presently. All that will be a bit cumbersome if @rprieto is inactive.

I think we should keep the officially sanctioned clients under the org. And move out all the exotic clients(elixir). Since I aim to make the node client pass all the official requirements, I would prefer it to be under the org. Many great products like protocol buffers, influxdb and other follow the same principle.

**Comment by zdroid** [comment]
Oh, you misunderstood it a bit. We didn't want to move any active client out of the organization. Just elixir.

**Comment by waldyrious** [comment]
I was the one who proposed that, @zdroid.

And responding to @agnivade,  I believe it's just a matter of moving them to whoever wants to take the role of maintainer. I don't think it's a good idea to keep them under the tldr organization, for several reasons:
- First, they're extra codebases to keep an eye on, resolve bugs and address feature requests, keep up to date with dependencies, etc.
- Second, by putting all clients on equal footing, we will be in better position to enforce the client spec in a neutral manner.
- And third, by decoupling the clients from the org, we would help people to stop associating the pages repository with the clients themselves, especially since many of them are named simply "tldr" or "tldr-pages". This should cut down on the misplaced issues in the pages repo that actually belong in the clients' repos.

But of course, I'm open to hear other thoughts about this.

**Comment by Leandros** [comment]
Thanks for pinging.
The homebrew repository can be removed, we could still use it for distributing any "beta" releases, but since you can specify to build master via homebrew I don't think it's applicable in our case.
Feel free to remove it.

**Comment by waldyrious** [comment]
Thanks for the confirmation, Leandros, I'll delete the repo. Let's continue the discussion about the default clients in #1056 (could you please copy your comment from #1115 into #1056? I think it is part of the same discussion -- if you'd like, change the title of the existing discussion to be more generic).

**Comment by waldyrious** [comment]
Ok, I've deleted the homebrew-tldr and tldr-cli repositories, and transferred the elixir client out of the org. I tried transferring it directly to @edgurgel, but Github only lets me transfer it to myself if moving from the org; but I can transfer it now from my account to @edgurgel's, which I just initiated (awaiting his confirmation).

Shall we close this one and continue discussion on #1056?

**Comment by agnivade** [comment]
> First, they're extra codebases to keep an eye on, resolve bugs and address feature requests, keep up to date with dependencies, etc.

But if we are the owners of those codebases, is it not the same either way ? Somebody has to do it anyway. Doesn't make much of a difference whether you do it inside the org or in a personal repo.

Agree on the other 2 points.

**Comment by zdroid** [comment]
Basically, all I wanted to be done here is done. Let's move on to #1056.

**Comment by waldyrious** [comment]
@agnivade the maintainers don't necessarily have to be the same people. See for example @Leandros who is maintaining the cpp client which he's suggested could become the official tldr client.
