### ISSUE TITLE
Tooling: check outdated page in PR with the English page as-is in PR

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#11830]
Right now, if you change the translated page as well as the English page, to match each other, the tldr-bot will warn you in the PR that the translated page is outdated. Using this issue, we want to check if we can use the English page as is in the PR-branch instead of main. This approach has the only con that we need to keep the PR-branch up-to-date with main otherwise we might miss out.

**Comment by kbdharun** [comment]
I would suggest checking if the English page exists in the PR first and comparing it to the translation. Having the branch synced with `main` isn't a con as it prevents conflicts in cases like these (when 2 PRs modify the same page).

**Comment by sbrl** [comment]
Hmmm. Sometimes you end up with conflicts against `main`, meaning you can't automatically merge. In which case, you may want to e.g. `git switch` to `main` to extract the relevant information before `git switch`ing back again.

But otherwise yes, this does seem like an edge case that could use fixing. I believe the code in question is <https://github.com/tldr-pages/tldr-lint> as [tldr-bot](https://github.com/tldr-pages/tldr-bot) just posts the comments.
