### ISSUE TITLE
Page modification request: duplicity

### ISSUE THREAD

**Issue by eliminmax** [tldr-pages/tldr#12615]
### Command description

The `duplicity` command-line backup tool's page exists, but is inaccurate.

It has an example of the `duplicity restore` subcommand with the non-existent `--path-to-restore` flag. The actual flag is `--file-to-restore`.

I use Duplicity version 0.8.22 packaged for Debian Bookworm. I confirmed that the upstream's current man page also has the same `--file-to-restore` flag, but not `--path-to-restore`.

### Documentation

https://duplicity.nongnu.org/vers8/duplicity.1.html

### Platform

Common

### VCS repository link (e.g. GitHub, GitLab)

https://gitlab.com/duplicity/duplicity

**Comment by eliminmax** [comment]
I'd open a PR to fix this, but I have a problem with the CLA. From the inclusive language section:

> "they" instead of "him"/"her"

It should be "them", not "they".

*(I'm mostly kidding here. I didn't see any issue category that seemed appropriate for that. Thanks for trying to foster an inclusive environment.)*

**Comment by tricantivu** [comment]
Hello @eliminmax! Thanks for opening the issue, I am the person responsible for the change in the page.

I believe such option may not exist because of a difference of versions. When I opened a pull request, the version I was using was 2.1.4.

Furthermore, [source code of `duplicity` explicitly states that the option `--file-to-restore` is deprecated](https://gitlab.com/duplicity/duplicity/-/blob/dev/duplicity/cli_main.py?ref_type=heads#L183).

I can create a pull request to attempt clarifying this discrepancy of options for users of older versions.

**Comment by eliminmax** [comment]
If you think that's appropriate. I though I'd done my due diligence, making sure it wasn't because Debian was packaging an older version. It looks like I messed that up, and looked at an older man page, thinking it was up-to-date. My bad.

**Comment by tricantivu** [comment]
> If you think that's appropriate. I though I'd done my due diligence, making sure it wasn't because Debian was packaging an older version. It looks like I messed that up, and looked at an older man page, thinking it was up-to-date. My bad.

No problem 🙂, people's feedback is important to keep the pages in good shape.

If you find anything else or want to contribute, do not hesitate.
