### ISSUE TITLE
Pager

### ISSUE THREAD

**Issue by sebelk** [tldr-pages/tldr#1281]
It would be nice that tldr supports pagers such as *less*

Greets!

**Comment by agnivade** [comment]
Can you clarify ? 

Do you mean a tldr page for the `less` command ? Or that the output of `tldr <command>` should be paged ?

**Comment by sebelk** [comment]
@agnivade I mean the output `tldr <command> `should be paged. Ok, I know that I could pipe it :)

**Comment by agnivade** [comment]
@sebelk - That really depends on the clients to implement it. Moreover, we have a hard limit of 8 examples. So I think rarely you will see content flowing out of screen so that you have to scroll. Paging for such an use case seems like an overkill. And I am not sure if paging works in Windows or not.

**Comment by agnivade** [comment]
@sebelk - I am going to close this one now. Feel free to reopen if you feel something else should be done here.

**Comment by pepa65** [comment]
BTW, in the [tldr-bash-client](https://github.com/pepa65/tldr-bash-client), when `less` is available, it is used when the page is larger than the display.
