### ISSUE TITLE
Typo on the README

### ISSUE THREAD

**Issue by alexaldearroyo** [tldr-pages/tldr#12811]
There is a typo in the installation guidelines within the README.md.

Regarding the installation through Homebrew, it says:

`brew install tlrc
`

Where it should say:

`brew install tldr`

**Comment by kbdharun** [comment]
Hi, thanks for the issue. The spelling is intentional (and not a typo), `tlrc` is our [official and actively maintained rust client](https://github.com/tldr-pages/tlrc) replacing the old client, the old `tldr` package name in Homebrew is our [C client](https://github.com/tldr-pages/tldr-c-client) which is currently unmaintained (and doesn't follow the latest client specification).

**Comment by alexaldearroyo** [comment]
Oh I see, perfect! Thank you for the clarification.
