### ISSUE TITLE
Git Checkout clarification

### ISSUE THREAD

**Issue by jeeftor** [tldr-pages/tldr#1351]
So i was contemplating adding:

`git checkout -b {{local_branch_name}} {{origin:remote_branch}}`

although we currently have:

`git checkout -b {{branch}}`

@waldyrious / @agnivade  what do you guys think?

I guess we could consider modifying the existing one to:

`git checkout -b {{branch}} {{Optional: Remote branch source}}` or something

**Comment by waldyrious** [comment]
So the idea is to allow checking out a branch using a different name than the upstream branch?

If so, I'm not really sure this is a common enough need to warrant inclusion in tldr. Do you need to do this often?

**Comment by waldyrious** [comment]
@jeeftor does #1359 affect this issue?

**Comment by agnivade** [comment]
@jeeftor - I think the current version of the git checkout page is good enough for a tldr level.

**Comment by waldyrious** [comment]
I agree with @agnivade. Coincidentally, earlier today I had to look up how to checkout a branch under a different name, and did look for that in the tldr page (I had forgotten about this discussion), yet I felt it was perfectly justifiable that it wasn't included. In fact, it's during daily usage like this that I come up with changes I submit as PRs, if I feel they warrant inclusion on the page, which clearly wasn't the case here. I'll close this, since the previous prompt went unresponded anyway, but we can always reopen if there's further arguments.
