### ISSUE TITLE
git diff: add relative time ranges examples

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1368]
git diff 'HEAD@{yesterday morning}'
    git diff 'HEAD@{3 days ago}'
    git diff 'HEAD@{one week ago}'

and 

    git diff --since="yesterday morning"
    git diff --since="3 days ago"
    git diff --since="one week ago"

From [this reddit thread](https://redd.it/69j3ir). Not sure exactly what the difference is between the two syntaxes, I'd need to investigate a bit. If anyone knows, please weigh in below!

For reference, here's the [current git-diff.md](https://github.com/tldr-pages/tldr/blob/73ec3a8811e679b84678a784c0ae4284078b1a84/pages/common/git-diff.md) page.

**Comment by mdew192837** [comment]
Here may be something useful. I'll take a look at this though.

**Comment by jitakirin** [comment]
BTW, I didn't have much luck with the `--since=` syntax with `diff`, it gives me empty results for any expression I tried. `git rev-parse --since='4 days ago'` gives `--max-age=1509142638`, so this works very well with `log`. For comparison `git rev-parse 'HEAD@{4 days ago}'` gives an actual commit ID.
