### ISSUE TITLE
STYLE-GUIDE: specify the usage of display, print, output...

### ISSUE THREAD

**Issue by Managor** [tldr-pages/tldr#13986]
Currently we require that help page is described with "Display help". It got me thinking that we don't have any consistent reasoning as to why we do that. This is really a post-hoc reasoning, but we could have a suggestion that "display" is used for either displaying visuals in a GUI or unchanging data like version numbers and help pages, and "print" is used for changing data like for example listing block devices, viewing configs, listing files in a folder, etc.

The definition of "unchanging" is very loose. Like for example the version number changes more than help pages. It'll be up to to the submitter to decide the cutoff point.

**Comment by blueskyson** [comment]
I don't think there is a need to change to other verbs. At least "display" is clear enough and it didn't cause a misunderstanding.

**Comment by Managor** [comment]
Fair enough. It would be nice to have a clear definition to when use "Display" though. Do you think unchanging data is a good guideline?

**Comment by renie** [comment]
I feel that in most of the cases `display`, `show`, and `print` (when not in a real printer), mean kinda the same, and we could use just one verb for those. And the definition could be something like: "When a command makes an information appear on screen."
However, when it comes to `list` I think we could keep it as it is, because it seems to be about "how" it appears to the user, like "It won't be tabular data, a json, csv, or a xml. Just simple items one after the other."
And about "changing" something or not, it does not sound to me it has anything to do with the verb used to say that "something will appear on screen". Like: `Shows/displays/prints current IPs.`, or `Switches network connection then shows/displays/prints new IPs.`
Does that make any sense?

**Comment by spageektti** [comment]
I agree with @renie

**Comment by Managor** [comment]
@renie The changing part refers to the nature of the data. The help page rarely changes from version to version. Version changes info changes only when a new version is released. On the other hand the output of journalctl, df or lsblk can change from minute to minute.

**Comment by renie** [comment]
@Managor ah ok. I think I got it now. The content being printed/shown/displayed might keep changing and should be updated on screen.
But I would say that even in those cases the verb used to describe the action of "letting an information appear on screen" could be any of those mentioned. We just to give some extra explanation about the updating process. Like "Shows/Displays/Prints, and keeps updating on every change/"x" minutes, the free space on disks".
Makes sense? Did I get what you mean correctly?

**Comment by Managor** [comment]
I said nothing about updating it on screen. Just that the data is relatively stable. The data will not change from one command use to the next. Using that as a justification, we can generalize the reason why we have standardized "Display help:".

**Comment by kbdharun** [comment]
> Currently we require that help page is described with "Display help". It got me thinking that we don't have any consistent reasoning as to why we do that. This is really a post-hoc reasoning, but we could have a suggestion that "display" is used for either displaying visuals in a GUI or unchanging data like version numbers and help pages, and "print" is used for changing data like for example listing block devices, viewing configs, listing files in a folder, etc.
> 
> The definition of "unchanging" is very loose. Like for example the version number changes more than help pages. It'll be up to to the submitter to decide the cutoff point.

We don't have it standardized across our pages because we generally tend to align the example descriptions with the command line usage or documentation upstream so that the users of specific CLI tools can correlate and understand it better. While standardizing it across the board is nice, it might be confusing for some commands and historical ones. So IG we can decide it on a case-by-case basis on the term that best fits the context.

**Comment by Managor** [comment]
@kbdharun What about standardizing just "Display"?

**Comment by kbdharun** [comment]
> [@kbdharun](https://github.com/kbdharun) What about standardizing just "Display"?

For this too, I think it is better to decide on a case by case basis since we already document it for help and version so if it works for other examples too the author is free to use the same.

**Comment by Managor** [comment]
Alright. I will close this as majority is against the idea.
