### ISSUE TITLE
"More information" links in alias pages

### ISSUE THREAD

**Issue by acuteenvy** [tldr-pages/tldr#14542]
Some alias pages have them, some do not. There are no documented rules for that.

The style guide is ambiguous, showing one example with the link and one without.
https://github.com/tldr-pages/tldr/blob/3eda65e26eb9b4f2bfcc9ee6118af8830fcb7f51/contributing-guides/style-guide.md#aliases

**Comment by sbrl** [comment]
It would probably be more consistent to remove more information links from alias pages, especially since alias pages are supposed to just simply 'alias' an alternate name for a command - if the command is different, then copy the page contents instead.

Can anyone dig up anything if there was a reason when alias pages were created for having the more information links on alias pages in the first place?

**Comment by Managor** [comment]
I'm for removal. Consistency is nice.

**Comment by acuteenvy** [comment]
All PRs have been merged.
