### ISSUE TITLE
Page modification request: gallery-dl

### ISSUE THREAD

**Issue by plshelpidkwhatimdoing** [tldr-pages/tldr#14996]
### Command description

Linked my update so it can be used:

https://github.com/plshelpidkwhatimdoing/pages/blob/main/gallery-dl.md

### Documentation

https://gdl-org.github.io/docs/

### Platform

Common

### VCS repository link (e.g. GitHub, GitLab)

https://github.com/mikf/gallery-dl

**Comment by Laaarge** [comment]
For next time, please follow the [contributing guidelines](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md):
- Your contribution doesn't follow the formatting restrictions, and 
- What you have done, is not the intention of this utility, as it is meant as a quick overview, you are going in too much details.
I've gone ahead and added some info output options in the current page, since i felt it is useful, in my pull request: tldr-pages/tldr/pull/15161]
