### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by yaquawa** [tldr-pages/tldr#1688]
I'v just installed tldr with `npm install -g tldr`.
But seems like the syntax highlight didn't work like the screenshot on the readme page.

![img](https://camo.githubusercontent.com/878ccf29c2a0f34a663b568604bfd26d76623f09/687474703a2f2f7261772e6769746875622e636f6d2f746c64722d70616765732f746c64722f6d61737465722f73637265656e73686f742e706e67)

**Comment by dospunk** [comment]
Providing some more information might be helpful

- What terminal emulator are you using?
- What OS are you using?
- Could you provide a screenshot of your output?
- Have you taken any steps to try and troubleshoot that have not worked?

**Comment by agnivade** [comment]
The screenshot uses a custom theme. By default we do not add any coloring because there are large varieties of terminals and themes. So adding any text coloring from itself might clash with the terminal theme.

Please look into this section - https://github.com/tldr-pages/tldr-node-client#configuration if you want to use a preset theme or even you can create your own theme.

**Comment by yaquawa** [comment]
@agnivade Problem solved ! Thank you so much!!

**Comment by agnivade** [comment]
That won't make a difference really. You still have to edit the `.tldrrc` file. 

I am a fan of softwares that just work out of the box without any need for configurations or customizations. Only if needed, the user should be able to configure it appropriately.
