### ISSUE TITLE
[Discussion] Commands that can't be shortened to a one-liner

### ISSUE THREAD

**Issue by Neph0** [tldr-pages/tldr#1744]
Hello,

I want to create an entry for `getopt`, which is a very useful program for shell programming, allowing you to cleanly inspect whatever command line arguments are being passed to your script. The main issue is that while its simple use can be shortened to a one-liner (`getopt -o f: -l file: -- "--file=abc"`), it's literally impossible to showcase how it's supposed to be used ([which whould be something like this, but more concise][1]).

What should the syntax be like, in cases like this?

Regards,

[1]: https://gist.githubusercontent.com/cosimo/3760587/raw/5ff226e47b56142e8f04d4d41c54ad4d5d5b21a6/parse-options.sh

**Comment by waldyrious** [comment]
Interesting question. We have considered how to handle nonstandard commands before, e.g. in #1130 and #1200, where we didn't get consensus to move ahead with adding a page that doesn't match the tldr format (a list of examples).

On the other hand, the project has successfully handled challenging commands like `git` (which requires multiple pages for its sub-commands), `less` / `vim` (whose "commands" are more like keyboard shortcuts inside an interactive session, than one-liner commands that can be on a regular shell), and `crontab` (whose tldr page describes the syntax of crontab entries), so it's not an intractable problem.

If you think you can propose a `getopt` page that conforms to the general format of tldr pages (a one-line description followed by a single-line command-ish entry), then by all means go ahead and submit a PR. The format is important because the tooling around the project (linter, clients, etc) is counting on it.

**Comment by Neph0** [comment]
> The format is important because the tooling around the project (linter, **clients**, etc)

Could you please expand on this? Are there people using `tldr` for more than a simplified and quick `man`-check from the command line?

**Comment by waldyrious** [comment]
> Are there people using `tldr` for more than a simplified and quick `man`-check from the command line?

It's not particularly about the ends, but the means. People have written [multiple](https://github.com/tldr-pages/tldr/blob/master/README.md#clients) [clients](https://github.com/tldr-pages/tldr/wiki/TLDR-clients) to cater to specific needs/wants, ranging from specific functionality (e.g. search, auto-update, easy installation, fewer dependencies...), to the programming language or frameworks used, to the environment it is to run on (OS, desktop / web / mobile, etc.).

These clients all follow the [current](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format) [syntax](https://github.com/tldr-pages/tldr/issues?q=label:syntax), and any change to that would involve making sure we don't inadvertently break them. See for instance the discussion at #958.

**Comment by Neph0** [comment]
That makes sense, thanks for the complete answer.

**Comment by waldyrious** [comment]
Thanks for understanding :) I know it's frustrating to want to extend tldr's convenient approach to other tools other than traditional commands, and be unable to do so.

It was good to have this discussion explicitly, as well, rather than split among various threads, so this will also serve as future reference. :books: :ok_hand:
