### ISSUE TITLE
[Discussion] Add a command-line option/syntax for tldr-style info regarding file extensions.

### ISSUE THREAD

**Issue by Neph0** [tldr-pages/tldr#1751]
I think that this project's scope could be extended a bit, by providing `tldr` informations about more than commands/softwares.

I just downloaded a `.tgz` file, which pretty much is a `.tar.gz` file. I typed `tldr .tgz`, but nothing came up.

Could we make this a thing?

Example:

```
# .tgz

> File archive created using Gnu Zip compression and a TAR archive.

- To uncompress "file.tgz":

`tar xzf {{file.tfz}}`
```

For other types of files, there could be some examples to show how to interact with such a file from the command line. Example:

```
# .a

> Archive library file, statically linked, generated from source code.

- To check the symbols-table of the static library "libtldr.a":

`nm {{libtldr.a}}`

- To see information regarding the library "libtldr.a":

`file {{libtldr.a}}`

- To generate such a file with `gcc` based on the code in "myLib.c":

`gcc -c -o myLib.a {{myLib.c}}`
```

Note that this doesn't break backward-compatibility, and any command starting with a `.` (dot) character would be treated as a file extension. There could be a different page-syntax for such entries, but I think the current one would still work well.

**Comment by Neph0** [comment]
Note that the command syntax would be anything starting with a `.` (dot) character.

**Comment by agnivade** [comment]
Hey @Neph0, you can do `tldr search ".tar.gz"` with the node client and you will get "tar" as the top result. This is the closest solution that I can think of.

I am a bit reluctant to add this feature because you are just matching tools with their associated file extensions. There are lots of tools which do not work on files at all. And there might be multiple tools which work on a single file type. Which page are we going to show in that case ? Moreover, unix generally, does not care about the file extension at all. As you will see in our CONTRIBUTING guidelines, we avoid mentioning the extension except when it makes things clear.

Even after ignoring the fact that this goes against the main motto of this project, i.e. - to be a man page supplement, there seems to be a lot of problems I listed above.

Keeping the above factors in mind, I am against adding this feature. Let me know your thoughts.

**Comment by Neph0** [comment]
The idea would just be to hand-pick a bunch of command-line programs, completely arbitrarily, to give an idea to the user about what he could use with this file.

It's true that the concept of file extension doesn't have much sense in an unix environment, but when you're a human being getting a file from someone else, you might not know what to do with it, unless it's properly tagged by its file extension :smile: 

Regarding your `search` bit:

``` bash
$ tldr search ".tgz"
Searching for: .tgz


Run tldr <command> to see specific pages.
$ 
```

**Comment by sbrl** [comment]
I like the idea! Perhaps we could have a `files` platform that contains information about file type extensions? The only websites that do this currently that I'm aware of aren't actually helpful and are stuffed full of ads.

I am aware though that this might be better as a sub-project of tldr perhaps though or something.

**Comment by agnivade** [comment]
> The idea would just be to hand-pick a bunch of command-line programs, completely arbitrarily, to give an idea to the user about what he could use with this file.

I do not see much benefit of this. More specifically, I do not see the value in this. Practically speaking, if I have a file and I don't know how to open a file, I will do a google search. So, I don't see tldr providing anything extra other than a unified place for the command examples and their file associations.

You are most welcome to use a pluggable add-on sort of approach. Feel free to use the "tldr.zip" file in the tldr-pages.github.io repo and from there you can build up an index for file extensions to pages. Now, whether they will be implemented in the clients or not is a different question and depends on the client owners.

> Regarding your search bit:

Yes, searching for ".tgz" doesn't give anything. It's not a perfect solution.

**Comment by Neph0** [comment]
> Practically speaking, if I have a file and I don't know how to open a file, I will do a google search.

You do realize that the whole point of the project is to skip the "read the man" and "search on google" steps when trying to figure something out on your computer?

**Comment by agnivade** [comment]
Yes, but I see tldr as something more than just a local cache of "search on google". We introduce simple commands first and then slowly build up to more complex examples with a beginner focused language. And we stress on using practical examples that users can quickly identify with rather than mentioning generic words.

This is something you won't get anywhere on google.

But, in the case of file associations, I don't see anything extra other than a local cache of whatever is already available online. The idea in itself is not bad. If we have a unified place which associates tldr pages with their file extensions, no harm in it. But the question of how to implement it is still not clear. And that is something to think about.
