### ISSUE TITLE
page request: guetzli

### ISSUE THREAD

**Issue by daylightbrightledlight** [tldr-pages/tldr#2181]
Command: `guetzli`
Repo: https://github.com/google/guetzli
Usage:
```
Guetzli JPEG compressor. Usage:
guetzli [flags] input_filename output_filename

Flags:
  --verbose    - Print a verbose trace of all attempts to standard output.
  --quality Q  - Visual quality to aim for, expressed as a JPEG quality value.
  --memlimit M - Memory limit in MB. Guetzli will fail if unable to stay under
                 the limit. Default is 6000 MB
  --nomemlimit - Do not limit memory usage.
```

Page:

```
# guetzli

> JPEG image compression utility.

- Compress a JPEG image:

`guetzli {{input.jpg}} {{output.jpg}}`

```

**Comment by sbrl** [comment]
Hey, thanks for the page request! Have you considered opening a pull request for this?

If you'd like to, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

Maybe we can also add those quality & no memory limit options in further examples too, since we haven't reached our limit of 7-8 examples yet.

**Comment by daylightbrightledlight** [comment]
So there are many commands that are available. I'm just going to get this page started.
