### ISSUE TITLE
Move @waldyrious to former maintainer

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#2257]
Hi, @waldyrious ! As you know, our
[governance guidelines](https://github.com/tldr-pages/tldr/blob/master/GOVERNANCE.md)
define processes for keeping the list of organization members
in sync with the actual maintenance team.
Since you haven't been active in the project for a while now,
we'll be moving you to the status of former maintainer.

In practice, not much will change on your side,
since you'll remain a collaborator in the repos you have been active in,
so **you will keep the ability to commit, merge PRs, label and close issues, etc.**,
if you feel so inclined. But even if you don't,
keep in mind that every bit of work you already did for the tldr-pages project
was a voluntary gift of your time to this community.
Your efforts have contributed to a project
which helps hundreds of people every day — be proud of it!

And of course, you're welcome back anytime as a maintainer, if you so choose
— in which case we'll re-add you to the organization,
as is also described in the guidelines.
In any case, we wish you the best of luck in your new endeavors!

**Comment by agnivade** [comment]
@waldyrious - Looks like you have accepted the invitation. Going to close out this issue now.

Hoping to see you back as a full time member soon !

**Comment by waldyrious** [comment]
Thanks for doing this, @agnivade -- it's my fault for not informing the community of my reduced availability, especially since I remained active elsewhere on github and gitter. I still have many plans for contributions I want to make to tldr-pages, so I'll definitely be returning as an active maintainer in the future.

It's been a while since I worked on the documentation, but I believe the steps listed [here](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#for-removing-inactive-organization-members) don't mention the specific steps of:
- actually removing the user from the org
- adding the user as a collaborator in the repos
- updating the list of current vs. previous owners (this one is mentioned but in an easy-to-miss form)

It's possible that these additions are being tracked in an issue, but if memory doesn't fail me, that's not the case. I think the instructions for removing owners should be listed in a step-by-step format similar to those for adding new owners.

For starters, I opened #2259 to make a few formatting changes to that document; I'd ask if you could add the remaining instructions afterwards, @agnivade (or @sbrl or @pxgamer) since I don't have access to the org management interface anymore to verify that the instructions are correct :)

**Comment by waldyrious** [comment]
Btw @agnivade I'm not sure if this is intentional but I only got an invitation to become a collaborator of the website repo (tldr-pages.github.io). I believe the guidelines may be a little ambiguous in this respect, but the passage [here](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#when-to-change-roles)

> If an organization member becomes inactive for over 6 months, their membership status should be equally deactivated. (They should nevertheless remain as collaborators in the repositories on which they have been active in the past.)

...doesn't apply any qualifiers to the "in the past", so I'd interpret it as not having referring to the same latest-6-months period (or other). Do you read it otherwise? Or are guidelines elsewhere that contradict my interpretation?

Or perhaps this is just a delay on Github's part?

**Comment by sbrl** [comment]
We'll be glad to have you back once you're ready, @waldyrious :smiley_cat:

With respect to updating `COMMUNITY-ROLES.md`, a tracking issue sounds great if you could open one. I'm a little fuzzy on the details myself - so I'd need some clarification on a few points if I  were to  attempt it myself.

**Comment by waldyrious** [comment]
Sure, will do. You being fuzzy in the details is precisely the type of situation we want to avoid with clearer documentation of the processes :)

**Comment by sbrl** [comment]
Thanks, @waldyrious :smiley:

**Comment by agnivade** [comment]
> I would suggest not closing these issues until the user has accepted the relevant invitations, 

Yes, I closed it once you accepted one of the invitations. Did not bother much with the other one since I thought you would be accepting that anyways after some time. But sure, its good to be done with everything and then close.

**Comment by waldyrious** [comment]
Yeah, I didn't mean to write that directed as you (I fully trust that you had no ill intentions :slightly_smiling_face:) but rather as a note to make sure that detail would be included in the more specific instructions that are now tracked in #2266.
