### ISSUE TITLE
Original Man Page

### ISSUE THREAD

**Issue by Jab2870** [tldr-pages/tldr#2654]
Do you think it would be useful to include a link to the original Man Page? This relates to #1082 .

I think we have decided in #2649 that links to the project page should go at the bottom of the description. If we are making this change, do you think it would make sense to do this at the same time?

```markdown
# x_x

> View Excel and CSV files from the command-line. 
> Homepage: <https://github.com/kristianperkins/x_x>.
> Man Page: curl(1).

- View an XLSX or CSV file:
```

or

```markdown
# x_x

> View Excel and CSV files from the command-line. 
> Homepage: <https://github.com/kristianperkins/x_x>.
> Man Page: <https://linux.die.net/man/1/curl>.

- View an XLSX or CSV file:
```

I couldn't find a man page for x_x so have used curl as the example.

**Comment by waldyrious** [comment]
Isn't the man page always accessed by running `man <command name>`? I don't think it's good use of space to include information that is essentially the same pattern for every page, since there's barely no new information added to what the page already contains (except perhaps an indication of whether the man page exists or not).

**Comment by agnivade** [comment]
Yeah, let's just go with the home page. Some pages don't even have a man page. If there is one, then one can always do `man <cmd>`, if there isn't, then there is the home page to look up.
