### ISSUE TITLE
page request: exec

### ISSUE THREAD

**Issue by TobiasRoland** [tldr-pages/tldr#2804]
It would be great with a page for the  exec command, the man page is... quite terse

https://linux.die.net/man/3/exec

**Comment by mttbernardini** [comment]
There's a PR for `exec(1)` (see #2800) but, seing the provided link, you seem to be referring to `exec(3)`, the family of C functions. I don't know if tldr pages about C functions and libraries exist yet. Maybe you could open an issue to see if there's any interest about it.

**Comment by sbrl** [comment]
Hey, @TobiasRoland! If you're after help for the console command, I'd recommend `help exec` instead of `man exec`, as it's actually a shell built-in.

As @mttbernardini mentions, we've already got a PR open for this in #2800.

If you're referring to the C function, then that's sadly out-of-scope of tldr-pages.

**Comment by sbrl** [comment]
Update: #2800 has been merged! That was fast.
