### ISSUE TITLE
ack: meaningless value

### ISSUE THREAD

**Issue by urbalazs** [tldr-pages/tldr#2805]
In [ack](https://github.com/tldr-pages/tldr/blob/master/pages/common/ack.md): `ack --ruby {{each_with_object}}`

What does it mean "each_with_object"? I tried to find out from [ack documentation](https://beyondgrep.com/documentation/), but without success.
Please use a more descriptive value name!

**Comment by agnivade** [comment]
ping @negamorgan

**Comment by negamorgan** [comment]
hey, I'll take a look at this today

**Comment by negamorgan** [comment]
I haven't looked at this in a long time, so I'm a little rusty, but AFAICT this is still a valid ack example of using ack's file types syntax `--ruby` to search for a ruby method `each_with_object` and return those results. 

What do you mean by value name? Is that the thing in the curly braces?

This example might be lost on people that don't understand ruby and ruby iterator methods, so I could update to something more widely understandable such as `ack --js {{forEach}}`. But the search term could really be anything since the relevant bit is that you are scoping to a particular file type with the file type option `--ruby`.

Anyway, let me know what you prefer. Happy to update this or have it replaced.

**Comment by agnivade** [comment]
Yes, we should simplify it further for people who might not have any programming experience in Ruby. For eg, I could not figure out that "each_with_object" is just a method name. If that is so, why not just name it "{{method_name}}" ? That clearly explains what the token value is and that it can be any method.

**Comment by negamorgan** [comment]
yep, makes sense. I'll submit a PR with a further simplified example like {{search_term}}, since it doesn't really need to be a method name.
