### ISSUE TITLE
Pages archive doesn't have index.json for other languages

### ISSUE THREAD

**Issue by pepa65** [tldr-pages/tldr#2829]
In the pages archive on `http://tldr.sh/assets/tldr.zip` only the English language pages/ directory has an index.json, the other languages don't. This will make it harder for clients to implement displaying pages in other languages when they rely on or use index.json.

**Comment by mebeim** [comment]
Hmmm, looks like the `index.json` package **does** contain information about all the languages, but unfortunately it is located under `/pages/` in the generated `.zip` file, when it should really be located at the top level of the ZIP. I am updating the build scripts to add an `index.json` at the top level of the ZIP.

Since some clients do actually rely on this file being located under the `/pages/` directory, I'll just create a duplicate for now and notify each of the clients to update the code and rely on the new one. When they do, we can remove the one in the `/pages/` dir.

I am creating a PR to address this issue and also a new issue to address the above (after the PR is merged) to act as a checklist for client support of this change.

**Comment by pepa65** [comment]
Right you are! Perhaps `pages/index.json` could be a symlink to `index.json`? Or should it just be left, as all the language info is indeed present in the right file, except it is in a less than ideal location??

**Comment by mebeim** [comment]
@pepa65 unfortunately ZIP files don't support symlinks. I just created #2829 to address this: the `/pages/index.json` file will stay there as a copy for backwards compatibility until the clients update.
