### ISSUE TITLE
Add @andrik and @Aracki as contributors

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#2988]
Hi, @andrik and @Aracki! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#2895, #2854, #2860, #2866, #2924, .... | #2478, #2503, #2582, #2616, #2617, .......)!
That qualifies you to become collaborators in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As collaborators, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as collaborators?

Either way, thanks for all your work so far!

**Comment by sbrl** [comment]
Invite sent, @andrik :D

**Comment by Aracki** [comment]
I share @andrik opinion. I will be honored to be part of the team.

Thank you guys for this. 😇

**Comment by waldyrious** [comment]
It warms my heart to hear those words, especially since our nitpicking in PRs has occasionally led some people to feel the contribution process was hostile or excessively cumbersome. I'm glad this the experience for most others (and you two in particular) has been more positive.

We're counting on you to to help making sure every contributor feels welcome and appreciated!

**Comment by sbrl** [comment]
Invite link sent, @Aracki :smiley_cat:
