### ISSUE TITLE
URL of commands

### ISSUE THREAD

**Issue by andrik** [tldr-pages/tldr#3027]
I noticed that @schneiderl and @pxgamer added URL to a lot of pages, so I was wondering if it's a good idea to add one more check to the linter or just put one more checkbox on the PR message.

Ideas?

**Comment by pxgamer** [comment]
I think it's worth adding them to the PR list. Regarding the linter, I'm not sure it's necessary unless we mark it as an optional thing.

**Comment by schneiderl** [comment]
Hi,
We had a conversation starting from [here](https://gitter.im/tldr-pages/tldr?at=5cd67f5c8fcdb05d47b79bf0) on gitter a few days ago about this exact topic. 

My feeling is that we should change the PR checklist and make the necessary changes to the style guide.

**Comment by andrik** [comment]
Oh great, I'll close the issue and follow there :+1:

**Comment by sbrl** [comment]
Sounds great, @schneiderl!

Yeah, I'm not sure updating the linter right now is a good idea. Since it's an optional feature, I'm not sure we need to lint it.

If we were going to, then I think we'd need a new linter first (maybe using Nearley as I mentioned [on the wiki](https://github.com/tldr-pages/tldr/wiki/Coding-projects#convert-the-linter-from-lexyacc-to-a-more-popular-language)).

**Comment by pxgamer** [comment]
If we did add it to the linter, it could be more of a lint to check it's the right format, rather than checking it exists.

**Comment by schneiderl** [comment]
> it could be more of a lint to check it's the right format

This is actually really good as I have seen commits with a wrong URL format happening (not once) here on tldr.

**Comment by waldyrious** [comment]
> Oh great, I'll close the issue and follow there 👍

I think this issue could remain open to track the addition of URL entry to the PR checklist and associated guidelines to the style guide.

**Comment by sbrl** [comment]
Ah, I see what you mean now @pxgamer - yeah!
