### ISSUE TITLE
About markown MD038 in common/sort.md

### ISSUE THREAD

**Issue by lord63** [tldr-pages/tldr#314]
in [common/sort.md](https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/common/sort.md), 

note there is a white space in the last command , so when you use `mdl` to lint the pages, you'll get MD038 warning, but this was excluded, any ideas? 

I'll create a PR latter, fix the white space and remove the MD038 if it is a problem.

**Comment by lord63** [comment]
ping @rubenvereecken

**Comment by rubenvereecken** [comment]
So apparently I explicitly excluded that warning in [`markdown-style.rb`](https://github.com/tldr-pages/tldr/blob/master/scripts/markdown-style.rb). The why isn't very clear anymore, although we did discuss it. Probably firstly because there were a tonne of those at that time.

I don't see why any command would absolutely require spaces inside backticks so I would consider removing it, though I find myself reluctant because I must have put it there for a good reason in the first place.

**Comment by lord63** [comment]
Yeah, that why I file an issue. We should find out the reason why we exclude this warning. If there is no need for this, I think we may remove it.

**Comment by rubenvereecken** [comment]
```
$ mdl pages | grep 'MD[0-9]\{3\}' -o | sort | uniq -c
     43 MD013
      1 MD038
```

Ok let's remove it, it's obviously not worth having as an exception.
