### ISSUE TITLE
How to change language using a client?

### ISSUE THREAD

**Issue by liuhaojava** [tldr-pages/tldr#3161]
How to Change Language?

**Comment by waldyrious** [comment]
According to the [client spec](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#language), it is expected that clients will determine what language to show based on the environment variables such as `LANG`.

@sbrl, wouldn't it make sense to also recommend a `--lang` or `--language` [CLI argument](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#arguments) to switch the language, just like we have `--platform` to override the auto-detected operating system?

(By the way, maybe we should define versioning for the spec, so that clients can indicate to users exactly what version they support and remain compliant even when future changes to the spec are introduced. What do you guys think?)

**Comment by mebeim** [comment]
Hi @liuhaojava, it depends on which client you are currently using. Not many clients support changing language or identifying language at all as of now. The only one which I am aware of is [`elecprog/tldr`](https://github.com/elecprog/tldr).

**Comment by mebeim** [comment]
Also, aren't we already versioning the client spec? I see it marked as v1.0.

**Comment by sbrl** [comment]
@waldyrious Thinking about it, it absolutely would (though you can always do `LANG=abc tldr example`, but that feels a bit weird). Have any clients actually added multi-language support yet? We've got quite a selection of translated pages to test with now.

I'll open a PR to update the client spec.

Maybe it's worth @mentioning client authors in the PR to make them aware of it.

**Comment by agnivade** [comment]
@liuhaojava  - I am going to close this now as your question has been answered. If you want details on a specific client, please feel free to open an issue in that client's repo. Thanks.
