### ISSUE TITLE
Localization for german language

### ISSUE THREAD

**Issue by pascaliske** [tldr-pages/tldr#3460]
First: This is a really awesome project - Thank you!

It would be nice if this documentation would be available in german also. 
Therefore I just wanted to promote myself as translator because I'm a native german speaker. 😄

As a beginning I would open some PRs for enabling the german language and translating the most common commands. Hope this is a welcome contribution. 🙂

**Comment by agnivade** [comment]
You are most welcome. Please feel free to take a look at - https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#translations.

However, please note that all clients do not support translations yet. So you might not be able to view this in your favorite client.

**Comment by pascaliske** [comment]
[Just pushed my first PR](https://github.com/tldr-pages/tldr/pull/3461) but it's still a WIP. 🙂

**Comment by zdroid** [comment]
> As a beginning I would open some PRs for enabling the german language and translating the most common commands. Hope this is a welcome contribution. 🙂

Danke für genau das! As far as I can tell, this is solved ever since [`pages.de/common`](https://github.com/tldr-pages/tldr/tree/master/pages.de/common) was created. Thus this issue is not needed anymore. You should continue translating the pages on the way as you have done so far.

I am closing the issue. If you have any more questions about the contributing process, feel free to ask them here or in another issue.
