### ISSUE TITLE
git-diff: exceed the number of examples

### ISSUE THREAD

**Issue by ivanhercaz** [tldr-pages/tldr#3753]
In 6a85525 I translated [`git-diff`](https://github.com/tldr-pages/tldr/blob/master/pages/common/git-diff.md), a page where are 9 examples for the command. Should we remove one of them? Maybe.. the fifth? I refer to the one dedicated to show just the filenames of the changed files:

```markdown
- Show only names of changed files since a given commit:
git diff --name-only {{commit}}
```
This issue is very relevant for me due I am translating all the `git` commands to Spanish (#3727), so I need to know if I should keep this in the Spanish translation or if we should change the English page to remove one and then commit another change removing it for the translation I did.

**Comment by zdroid** [comment]
We should... now the question is, how did this page pass the lint test?

**Comment by mebeim** [comment]
@zdroid that's because it is a Spanish page, and pages of various languges are not linted:

https://github.com/tldr-pages/tldr/blob/13feab2bfda2ffdfaf97468ca178182c5b6463cb/scripts/test.sh#L14

This requires an update of [the linter](https://github.com/tldr-pages/tldr-lint) since it is broken for a large number of Unicode characters.

**Comment by agnivade** [comment]
I'm okay with removing the 5th or any of the last 2 examples.

**Comment by zdroid** [comment]
By mistake I pushed to master again, so it got closed automatically.
