### ISSUE TITLE
TLDR for Vim has too many tips about things inside Vim

### ISSUE THREAD

**Issue by ryanolsonx** [tldr-pages/tldr#3779]
When I look at `tldr vim`, I see that it has many tips that tell you how to do things in Vim, rather than using the `vim` command itself.  I feel like there are more tips that we can add that are really useful. It's already at its max (of 8) items.

What should we do?

**Comment by zdroid** [comment]
Are there any examples you have in mind? It'd much easier if you outright suggested them here or in a PR, so project maintainers could review them as well.

Otherwise, it's a general policy not to change things unless there's a better alternative. (that's the conclusion I have come to, but it may not reflect the opinion of others) :smile:

**Comment by ryanolsonx** [comment]
OK! I'll make a PR and we can discuss a change or two I would make.

**Comment by ryanolsonx** [comment]
https://github.com/tldr-pages/tldr/pull/3783

**Comment by zdroid** [comment]
Does #3783 resolve this issue, or only a part of it? If it does resolve the issue, you can put `Closes #3779` in your PR's description.

**Comment by ryanolsonx** [comment]
I think it does, for now.

**Comment by jxu** [comment]
I am a vim beginner but I agree.
- Entering text editing mode is covered by description. 
- <Esc> is not needed normally for commands
- Instead of yank or delete current line, have a quick reference for most useful copy-paste commands: (y)ank, (x)cut, (p)aste, (d)elete, all of which are used in (v)isual mode
- include Ctrl-r for redo along with undo
- `:vs file` I find useful
- save and quit can be done with `:x`

**Comment by sbrl** [comment]
Not a vim user, but I can see your point. tldr pages should focus on the command itself, not how to use the program itself (though it's always on a case-by-case basis).
