### ISSUE TITLE
Add a notice for page changes in all languages

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3796]
This is a feature request, to automatically note a translated page should be fixed once the English version is changed.

Example: `{{git checkout}}` changed to `{{git-checkout}}` in #3795.

**Comment by ivanhercaz** [comment]
How should be note the change? Should a bot opens an issue?

**Comment by zdroid** [comment]
Maybe that way, this is open for discussion.

**Comment by ivanhercaz** [comment]
I could work on this if we reach a consensus about it.

**Comment by zdroid** [comment]
That's good to hear. What we really need is the automation of the review process. :P

**Comment by agnivade** [comment]
This should be fixed when our translation process is streamlined. But it's currently stuck now. So automation is all we can do for now.

Hooking up github webhooks to the tldr bot is one way to go. It can detect changes and comment on that PR itself.

**Comment by sbrl** [comment]
Hrm. Yeah - we tried p4oa or  whatever it was called, but ran into nasty difficulties. Perhaps GH automation is the way to go - at least for now.

That's a good idea @agnivade. Perhaps when an English version of a page is updated, it could comment on the PR that added the translation, and @mention a bunch of people (say like the 5 most recent?) that most recently contributed translations to that language to gain additional visibility?

**Comment by zdroid** [comment]
Check #2793 @sbrl

**Comment by schneiderl** [comment]
I like the idea of having a bot commenting on the PR that changes a certain page. 
I'm unsure that mentioning some people is the best way to notify translators, though. 

I feel like it would just end up flooding translators notifications and after a while, those notifications would become to get ignored.

As a translator would prefer to actively go after a list of recently changed pages instead of getting bothered with notifications that might not be my priority at the time.
Not sure how that would work, though.

**Comment by zdroid** [comment]
Maybe just a `translation` PR tag would be enough.

**Comment by zdroid** [comment]
This is actually rendered obsolete by #3591. A translating service solves all the issues I've described.
