### ISSUE TITLE
How to cache a single language?

### ISSUE THREAD

**Issue by stevemao** [tldr-pages/tldr#3860]
The spec says

> Caching SHOULD be done according to the user's language configuration (if any), as to not waste unneeded space for unneeded languages.

But the only asset you can download is tldr.zip, which is an entire archive. Is there anything I miss here?

**Comment by sbrl** [comment]
Hey there, @stevemao! Hrm, that's an interesting one. Looking at the git blame, think it was @mebeim and myself who appear to have added that to the specification.

You raise a good point.

I suppose you could download the whole thing, but only extract the bits you're interested in for now?

It might be worth doing something about this actually - especially since we're growing both the number of different translations and the number of translated pages.

**Comment by mebeim** [comment]
The current intended way is indeed downloading the whole archive and extracting only the languages of interest.

**Comment by schneiderl** [comment]
I agree with @sbrl when he says we could do something about this. 
Maybe making available an asset for each language and another one for the full archive so that the clients can cache the way they prefer.

**Comment by zdroid** [comment]
@schneiderl's idea is good. It'd also allow us to keep an old archive in the same place, giving clients the time to comply with the new page structure (which we've been discussing for a long time).

**Comment by kbdharun** [comment]
@stevemao I have some good news for you. Since [v2.0](https://github.com/tldr-pages/tldr/releases/tag/v2.0) (#10555) we support caching for individual languages.

This is the updated caching spec

_If appropriate, it is RECOMMENDED that clients implement a cache of pages. If implemented, clients MUST download the entire archive either as a whole from **[https://tldr.sh/assets/tldr.zip](https://tldr.sh/assets/tldr.zip)** (Which redirects to [https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr.zip](https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr.zip)) or download language-specific translation archives in the format `https://tldr.sh/assets/tldr-pages.{{language-code}}.zip` (Which redirects to [https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.{{language-code}}.zip](https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets)), along with the archive for English from **[https://tldr.sh/assets/tldr-pages.zip](https://tldr.sh/assets/tldr-pages.zip)** (It redirects to [https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.zip](https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.zip))._

_Caching SHOULD be done according to the user's language configuration (if any), to not waste unneeded space for unused languages. Additionally, clients MAY automatically update the cache regularly._
