### ISSUE TITLE
Implement organization level sponsorship

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#4057]
Gotta keep up with the trends:
https://github.blog/2020-05-12-github-sponsors-is-out-of-beta-for-sponsored-organizations/

**Comment by sbrl** [comment]
We're currently using Liberapay for this @zdroid? Ref #3102

**Comment by zdroid** [comment]
Check in the post. There's a way to make the button appear on the organization level too, not only on the repo level.

**Comment by sbrl** [comment]
Oh,  nice! I must have misunderstood what you were referring to. It looks like it's GH sponsor exclusive though? At least the instructions for users of other things aren't clear

**Comment by zdroid** [comment]
@sbrl I'm not completely sure, since I am not experienced with the sponsorship workflow.

cc @owenvoke @mebeim who may help more on this

**Comment by owenvoke** [comment]
I think at the time we decided that organisation level sponsorship through GitHub Sponsors wouldn't work for tldr pages. 🤔 Also, just to flag up that because of this, we never joined the waitlist.

I guess if we did decide to use it, we could possibly set it up using the ["Fiscal bank" option](https://github.blog/2020-03-24-getting-started-with-github-sponsors/#orgnobank) which allows you to forward to services like [Liberapay](https://liberapay.com/tldr-pages) as far as I can tell.

We should be able to get started through https://github.com/sponsors/tldr-pages/waitlist, however I'm not sure of the details that would be best to use. 🤷

**Comment by zdroid** [comment]
@owenvoke This actually may be as easy as making a `tldr-pages/.github` repository with `FUNDING.yml` in it. Do you want to give it a try?

**Comment by owenvoke** [comment]
Repository created @zdroid (https://github.com/tldr-pages/.github), that is now showing the sponsors button across all our repositories, but not on the main org page.

**Comment by zdroid** [comment]
That's a good move forward. We may use that `.github` directory for other organization-level things as well. If the process of adding an org-level sponsorship is too hard / complicated, maybe we don't really need it.

**Comment by sbrl** [comment]
Ah, I didn't  know about that `.github` repo thing. That's probably the best place to keep the sponsor button stuff I think.

I think at the moment the liberapay solution should work fine. We haven't gotten any sponsors yet though, so we'll have to wait and see :P

**Comment by zdroid** [comment]
Not worth the hassle. We already achieved 99% of the functionality by creating `.github` repository.
