### ISSUE TITLE
Grammar in French - verbs

### ISSUE THREAD

**Issue by ivorysoap** [tldr-pages/tldr#4714]
In the French translations, some pages use infinitive verbs while others don't.  Example:

 [ftp.md](https://github.com/tldr-pages/tldr/blob/master/pages.fr/common/ftp.md) uses infinitive verbs:
* **Passer** au mode de transfert binaire (medias, fichiers compressés, etc) :
* **Transférer** plusieurs fichiers sans demander de confirmation pour chaque :
* **Télécharger** plusieurs fichiers :

[cat.md](https://github.com/tldr-pages/tldr/blob/master/pages.fr/common/cat.md), doesn't:
* **Affiche** le contenu d'un fichier sur la sortie standard :
* **Concatène** le contenu de plusieurs fichiers vers le fichier de destination :
* **Ajoute** le contenu d'un ficher à la fin du fichier de destination :

Should we agree on a standard format, or does it not make a difference which one is used?
______________________

J'ai remarqué que la conjugation des verbes peut varier dans certains fichiers.  Par exemple:

Dans [ftp.md](https://github.com/tldr-pages/tldr/blob/master/pages.fr/common/ftp.md), on utilise l'infinitif:
* **Passer** au mode de transfert binaire (medias, fichiers compressés, etc) :
* **Transférer** plusieurs fichiers sans demander de confirmation pour chaque :
* **Télécharger** plusieurs fichiers :

Par contre, dans [cat.md](https://github.com/tldr-pages/tldr/blob/master/pages.fr/common/cat.md), on l'utilise pas:
* **Affiche** le contenu d'un fichier sur la sortie standard :
* **Concatène** le contenu de plusieurs fichiers vers le fichier de destination :
* **Ajoute** le contenu d'un ficher à la fin du fichier de destination :

Pensez-vous qu'on devrait s'entendre sur un format standard?

**Comment by mebeim** [comment]
Hi @ivorysoap, thanks for asking. I hope it's okay for you if I answer in English. I can mostly understand written French, but I don't speak the language so I definitely cannot write in it. If you know English well enough, I would ask you to please write in English so that the most people (specially the maintainers) can understand.

We definitely prefer present indicative (présent de l'indicatif) for verbs in command descriptions. If you read through the English pages, you'll notice that this is the most common form. Unfortunately not a lot of people speak French here (somebody amongst the contributors to the repo does, but nobody amongst the members of the tldr-pages org), so that's why you might see some inconsistencies here and there.

Feel free to open a PR to correct those verbs changing them from infinitive to present indicative. If you want to contribute additional French translations, you should prefer using present indicative instead of infinitive.

**Comment by ivorysoap** [comment]
Hi @mebeim, thanks for the quick response, and English is totally fine (I edited my comment to add an English version so others can see too).  Sounds good, I'll be sure to use present indicative for future contributions.

**Comment by sbrl** [comment]
I don't speak the language, but thanks for opening an issue. I'd suggest @mentioning some of the other french translation contributors :-)

**Comment by mebeim** [comment]
Closing this as the question has been answered.
