### ISSUE TITLE
Make the upper limit for the number of examples soft

### ISSUE THREAD

**Issue by rickythefox** [tldr-pages/tldr#4947]
Most commands follow the Unix philosophy of doing one thing and doing it well. Othes have more functionality and thus more ways to use them (`ssh-keygen` and `openssl` come to mind). I think that for these the upper limit of eight examples is not sufficient. Referring users to `man` in this case is even worse - the man pages for these super-tools are usually rather long and hard to navigate - an issue tldr is here to solve in the first place. Should exceptions to the eight-example-rule be allowed in these cases?

**Comment by sbrl** [comment]
Hey there, @rickythefox! We like to keep the example limit hard, because it helps to distill a command's functionalit into the 8 most useful examples. Generally, with commands such as `openssl` and `docker` they have many subcommands - but these can be documented in separate subpages.

Of course, there are exceptions like `awk` and `sed`, but in these cases we keep in mind the beginner user in particular when choosing the 8 examples to show.

**Comment by bl-ue** [comment]
> Generally, with commands such as openssl and docker they have many subcommands - but these can be documented in separate subpages.

Excellent point @sbrl, I think that's what @rickythefox (and myself frequently, too) is missing here.
