### ISSUE TITLE
Page request: i3

### ISSUE THREAD

**Issue by FukurouMakoto** [tldr-pages/tldr#4951]
I haven't seen anything in the current repo for [i3](https://i3wm.org/docs/userguide.html), so I'd like to do one if that's the case. 
If possible however I would like some guidance on this. 
For this command, mod1 by default is the Super key and is customizable by the user. 
This being the case, if I am to write the guide, should I use the default mod1 key or should I label it as Super?

**Comment by sbrl** [comment]
Hey, it'd be great if you could write a page for that! Don't forget that tldr-pages is command based, so you'd want to document the functionality of the associated commands in different pages, rather than the keyboard shortcuts. This said, we do have examples of pages that document keyboard shortcuts - `vim` comes to mind off the top of my head. So in this instance you'd want to document the command that starts the Window manager, and then use any extra examples at the end of the page (since we have a limit of 8 examples per page) to document keyboard shortcuts.

Regarding which keys to document, I'd suggest documenting the default key bindings - so I'd label it as the super key there.

**Comment by bl-ue** [comment]
@FukurouMakoto thank you for fixing this!  Next time when you open a PR that fixes an issue add "Closes #<issue number>" to the end of the description so that GitHub will automatically close the issue when the PR gets merged.  I see you opened #4960 to fix this but the issue was left open because GitHub didn't know this issue and that PR were related.
