### ISSUE TITLE
Pages where the title does not match the filename

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr#5071]
I originally posted this in https://github.com/tldr-pages/tldr-lint/issues/32#issuecomment-753515366, but moving this into an issue in the main repo to give it more visibility and community feedback.

One of the open issues for tldr-lint is https://github.com/tldr-pages/tldr-lint/issues/26: "Assert that the filename is the same as the page title". On implementing this lint rule, it introduces the following error against 7 pages. I have listed the 7 pages below, and what I think might make sense to resolve each.

The pages probably have a straight forward solution:
* `../tldr/pages/common/g++.md:0: TLDR108 Page title should match file name`
    * Page is titled `gplusplus`, this could probably just rename title to `g++`?
* `../tldr/pages/common/gpg2.md:0: TLDR108 Page title should match file name`
    * Page is titled `gpg`, this could probably just be change title to `gpg2`? All examples use `gpg2`, though convention between `gpg` and `gpg2` at this point is muddled as increasingly `gpg` == `gpg2` while the original `gpg` is just referenced as `gpg1`.
* `../tldr/pages/common/rg.md:0: TLDR108 Page title should match file name`
    * Page is titled ripgrep, probably just rename title to `rg` and then add ripgrep to the description? 
* `../tldr/pages/common/stolonctl.md:0: TLDR108 Page title should match file name`
    * Page is titled `Stolon` which is the name of the service, probably just change title to `Stolonctl` and add `Stolon` to description?

These three pages are a bit weird:
* `../tldr/pages/linux/file-rename.md:0: TLDR108 Page title should match file name`
* `../tldr/pages/linux/perl-rename.md:0: TLDR108 Page title should match file name`
* `../tldr/pages/linux/prename.md:0: TLDR108 Page title should match file name`

In each case, the installed command is `rename`, but the different filenames is necessary as these are all floating around and in common-use. Probably just rename the title in all cases, and not sure how important that the title matches the command in the examples versus matching the filename?

**Comment by bl-ue** [comment]
@MasterOdin, it's interesting that you brought this up, because I was earlier today thinking about proposing to remove the title entirely.  It really doesn't make that much sense to have it, because the clients themselves can easily add it.  It also prevents discrepancies like the ones you've pointed out.

**Comment by bl-ue** [comment]
>Page is titled ripgrep, probably just rename title and then add `rg` to the description?

Do you mean "add `ripgrep` to the description"?

**Comment by bl-ue** [comment]
@navarroaxel thoughts?

**Comment by MasterOdin** [comment]
> >Page is titled ripgrep, probably just rename title and then add `rg` to the description?
> 
> Do you mean "add `ripgrep` to the description"?

Yup, fixed.

**Comment by navarroaxel** [comment]
I think the title is a basic lint or rule when you create a `markdown` file, so if someone wants to use the pages from `tldr` to build some website (e.g using jekyll) we need to have a title to avoid extra code.

**Comment by bl-ue** [comment]
I never thought of that.  Good point.  I wasn't even thinking of the pages in terms of basic markdown files.

**Comment by bl-ue** [comment]
@MasterOdin, here's what I've concluded, please correct me if I'm wrong:

1. For `g++`/`gplusplus`, change the title to match the filename, `g++`. If the filename can have `+`'s in, so can the title.

2. For `gpg2`/`gpg1`/`gpg`, [`gpg.md`]() and [`gpg2.md`]() are identical execept for example and wording choices.  I think one of them should be removed, and the other one renamed to `gpg.md`.  The title should match.

3. For `rg`/`ripgrep`, as the command is `rg`, so should the page name and title.  I think mentioning that it's `ripgrep` in the description is a good idea.

4. For `stolonctl`/`Stolon`, the title should be `stolonctl` since that's what the filename and command name are. The description should probably contain something like `manages the Stolon service` somewhere.

5. For `file-rename`/`perl-rename`/`prename`, I agree with you that they're weird.  They're all the exact same command, but with different names.  Since on the different Linux distros they have different command names, make each title the same as the page name, since that's what the command itself is.

**Comment by bl-ue** [comment]
@navarroaxel do we support symlinks, so `gpg2.md -> gpg.md`?  It seems like we should.  Maybe I should open a separate issue for that.

**Comment by MasterOdin** [comment]
I am very much against symlinks in git repos as they do not work on Windows machines using cmd.exe (which I use here and there). I would ask very much that they do not be added here. If anything, I would suggest modifying `gpg2.md` to just say "Please refer to gpg instead for documentation" instead of the symlink.

**Comment by bl-ue** [comment]
I think so too @MasterOdin, I was just wondering if we have some solution that I'm not familiar with that @navarroaxel would point out.  As for modifying `gpg2.md`, it seems to me like we should probably just make them indentical, because that's what we do here.  (That should eventually be improved...)

**Comment by owenvoke** [comment]
I think it's worth keeping the seperate `gpg` and `gpg2` pages. 👍🏻 And we can just have the title as the same as the page title. I think there's nothing wrong with it being `gpg2` (people still know it's GPG). We could even have a note in each page saying something such as this:
> See `gpg2` for GNU Privacy Guard 2.

**Comment by sbrl** [comment]
I think @bl-ue and  has the right idea there.

1. `gplusplus` → `g++`
2. `ripgrep` → `rg`, but mentioning `ripgrep` in the page content
3. `stolonctl`: rename filename and title to the exact name of the command

GPG: @owenvoke's suggestion is sensible here. Let's keep separate `gpg` / `gpg2` pages, with `See also` references.

The `rename` situation is altogether very odd, and I'd need to read up on our previous discussions there to remember what was done.

**Comment by bl-ue** [comment]
@sbrl #3125, #3126.  We should probably just set the title to the page name, and since they're the same thing mirror the contents among the three.

**Comment by waldyrious** [comment]
I agree with what's been said above for the less tricky cases.

As for the `rename` pages, I'll copy my comment from [here](https://github.com/tldr-pages/tldr/issues/5085#issuecomment-756320458):

> maybe we can come up with a strategy that allows for disambiguation in all cases. Typically package managers use namespacing to resolve this issue, i.e. the tool is referred in the format `@owner/tool` or `@project/tool`. We already a version of this, somewhat, by splitting the tools by platform. We could further use the owner/project prefix for those that still conflict (i.e. `project-tool.md`, or `tool.project.md`). Thoughts?

**Comment by MasterOdin** [comment]
This issue was not resolved by #5377. The `rename` pages retain having a filename that differs from the page name. Additionally, tldr-lint 0.0.10 does not include any sort of check on ensuring the page name and filename match.

**Comment by bl-ue** [comment]
You're right. I forgot about all that 😕

**Comment by bl-ue** [comment]
We could use the alias stuff for them, possibly.

**Comment by bl-ue** [comment]
I'll clean up the rename situation within this next few days.  Looks like it could really benefit from the alias system we've devised recently. 👍🏻

**Comment by owenvoke** [comment]
Not really sure the alias stuff would work, as it's not an alias. It's 2 different versions of `rename`. ☹️ Or do you mean having just a reference to the other page?

**Comment by MasterOdin** [comment]
While they all use the same command, they are from different places, so they're not quite true aliases though.

**Comment by bl-ue** [comment]
Well, these three are identical, except for their name and origin:
- [`pages/linux/file-rename.md`](https://github.com/tldr-pages/tldr/blob/585e1415c9914457a6fabcee322659845dbd7288/pages/linux/file-rename.md)
- [`pages/linux/perl-rename.md`](https://github.com/tldr-pages/tldr/blob/585e1415c9914457a6fabcee322659845dbd7288/pages/linux/perl-rename.md)
- [`pages/linux/prename.md`](https://github.com/tldr-pages/tldr/blob/585e1415c9914457a6fabcee322659845dbd7288/pages/linux/prename.md)

They could definitely be condensed into one page and two aliases with nothing but benefits in every way.

We could easily add the origin notes (e.g. `NOTE: this page refers to the command from the prename Fedora package.`) to the alias pages themselves, I'd say.

Also, these pages look to me to be the exact same, `rename` from `util-linux`.  I'm guessing that because of the note in the one and the [conversation here](https://github.com/tldr-pages/tldr/issues/4218) regarding the other.  They should probably be merged into one, in `pages/common/rename.md`.
- [`pages/osx/rename.md`](https://github.com/tldr-pages/tldr/blob/master/pages/osx/rename.md)
- [`pages/linux/rename.md`](https://github.com/tldr-pages/tldr/blob/master/pages/linux/rename.md)

**Comment by sbrl** [comment]
Oops! That might have been a typo or misunderstanding on my part. Sorry!

**Comment by Managor** [comment]
I'm closing this as outdated. Please open a new issue so that the conversation is fresh.

There is one related issue here https://github.com/tldr-pages/tldr/issues/12777
