### ISSUE TITLE
American vs. British English spelling differences

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5221]
We ought to normalize the [American vs. British English spelling differences](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences) of words across all of our English pages.

For example: organization vs. organisation, color vs. colour.

Question is: which to go with?

**Comment by bl-ue** [comment]
I'm inclined to pick the American spelling, because:
1. You can probably guess # 1 :smile:
2. It's more common across developer-oriented sites and projects
3. It's what we use in our official documents like [`COMMUNITY-ROLES.md`](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md)

**Comment by bl-ue** [comment]
Once decided, I will take the issue in hand ;)

**Comment by sbrl** [comment]
This was discussed previously I think. It was decided that we should use American English. I'm in the UK myself, so I don't always remember.

**Comment by bl-ue** [comment]
Perhaps here: https://github.com/tldr-pages/tldr/pull/294#discussion-diff-37821775

**Comment by sbrl** [comment]
Wow, great searching skills! That wasn't the one I was thinking of, but it'll definitely do as input here. I would guess from reading that the general consensus is to correct things when we see it, but don't go out of our way to change it.

**Comment by bl-ue** [comment]
So you don't think I should open a PR to normalize this?

**Comment by sbrl** [comment]
Hrm, I'm not sure. Let's wait for others to weigh in on this.

**Comment by waldyrious** [comment]
My hat's off to you, @bl-ue — great searching skills indeed! 😮

I stand by my suggestion in that thread that US English is more prevalent online, despite not being the "original" (the same way that [Brazilian Portuguese is more prevalent than Iberian Portuguese](https://knowyourmeme.com/photos/1193909-polandball) 😅) so if we're to pick a default, I'd argue that it should be en-US.

That said, I don't feel too strongly about this, so not enforcing any standard would probably be just as fine (it's not like anyone will fail to understand a tldr page if it spells "colour" instead of "colour", after all).

**Comment by bl-ue** [comment]
Okay, then I'll close this issues as I'd say a consensus has been reached.  I'll not go normalize them, I'll just fix silenty them in PRs (maybe).

**Comment by sbrl** [comment]
Agreed - I don't think it's particularly important to standardise this.
