### ISSUE TITLE
Add organization owner: @einverne

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5414]
Hi, @einverne! You've been an active tldr-pages organization member for over 6 months (actually 14!!).
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by owenvoke** [comment]
14 months? 😮 Wow, we need to automate this! Congrats @einverne.

**Comment by waldyrious** [comment]
Hmm, I suppose it might make sense to clarify the guidelines for this type of transition. The primary motivation for the role transition process is to allow people to perform the roles they show interest in doing, not merely react mechanically to the passage of time or unrelated activity. In particular, this bit from [`COMMUNITY-ROLES.md`](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md):

> rather than assigning roles and tasks to people, these guidelines aim to recognize the work that people already do. Everyone is therefore encouraged to get involved and contribute to the project in whatever way they prefer, and we will strive to get barriers out of the way of these contributions.

and later on:

> Organization members who remain active for a while should become organization owners. Specifically: members of the tldr-pages organization who remain active for at least 6 months (see MAINTAINERS.md) should be invited to become an owner of the tldr-pages organization. This means they will be able to add people to the organization, manage all the organization's repositories, configure integrations, etc.

Now, while @einverne hasn't been completely absent for the past 6 months, he hasn't been what I'd unambiguously call "active" either ([2 commits in the past 6 months](https://github.com/tldr-pages/tldr/commits?author=einverne&since=2020-09-13&until=2021-03-13), and no participation in the Gitter chat, to name two easily verified activity proxies). He also, to my knowledge, hasn't expressed interest in performing the actions that being an owner would allow him to do, as quoted above.

To be clear, **this is not a bad thing!** Everyone is welcome to participate at a rate compatible with their interests and availability. I am just concerned that he doesn't seem to have shown particular interest in deepening his involvement with the management of the project.

This is not to say that I object to making him an owner. I fully trust his judgment and competence. I am, however, wondering if following the process blindly as we're kind of doing here, actually introduces churn (creating this issue, assigning permissions, editing MAINTAINERS.md, and most importantly, loading a bunch of additional expectations upon his shoulders) rather than remove barriers that would otherwise impede his natural participation drive. I'd love to hear your thoughts, and of course, @einverne himself :)

**Comment by bl-ue** [comment]
Just a note @waldyrious: @einverne has been more active than it appears, approving and merging PRs regularly (https://github.com/tldr-pages/tldr/issues?q=einverne may give a hint)

**Comment by waldyrious** [comment]
That's an excellent point, @bl-ue! Indeed I missed some of his activity.

That said, I want to reiterate that I'm not objecting to @einverne's role change in particular — if he's up for it, then by all means, I'd be thrilled to see the maintenance team continue to grow! ❤️

What I wouldn't be thrilled about is the prospect of potentially pushing people into positions they haven't shown interest in being. I got that impression (mistakenly, it seems) that it could be the case here, so I thought it was worth raising a possible clarification to the guidelines to ensure we trigger these processes when appropriate. I still think that discussion may be worth having even if it doesn't apply in this particular case. Do you have any thoughts in that regard?

**Comment by bl-ue** [comment]
Nope.  I think we (maybe just you and the others, I'm pretty new here) should discuss it at some point.

FYI—I did give it some thought before I opened this issue, because I know what you mean.  For example, @ivanhercaz has been an org member a week or two longer than @einverne, but since he's been less active I thought it would be good not to bother or pressure him. 👍🏻

**Comment by einverne** [comment]
Thank @bl-ue for this nomination. But as @waldyrious said, I personally like to review and merge people's pull requests more. And this is how I participate in the project in the past few months. I'd like to keep my position.

**Comment by bl-ue** [comment]
@einverne are you sure...? It seems to me (no pressure intended 🙂), once you're an org member, becoming an org owner simply gives you a few extra permissions, including a quite useful one: force-merging PRs though the CI checks aren't green or the approval minimum isn't met.

**Comment by einverne** [comment]
> @einverne are you sure...? It seems to me (no pressure intended 🙂), once you're an org member, becoming an org owner simply gives you a few extra permissions, including a quite useful one: force-merging PRs though the CI checks aren't green or the approval minimum isn't met.

Yes, I'm sure. And I think I do not need the force-merging permissions. In my opinion, if the CI broke, the best way is to check what's wrong and fix it. And I think the best for the community is to have more people to review and discuss.

**Comment by bl-ue** [comment]
Okay, thank you for confirming.  Then I guess we should close this issue 👍🏻

**Comment by waldyrious** [comment]
@einverne thanks for confirming my suspicions, and please excuse any hints my words may have given of disapproval of your work — I know it's hard to disagree online without conveying a negative connotation. I have great respect for the work you've done here — that which I've had the chance to review, anyway! 😅

> including a quite useful one: force-merging PRs though the CI checks aren't green or the approval minimum isn't met.

@bl-ue I must confess I am quite concerned about your insistence in this particular type of action. You've shown such interest more than once before, e.g. [here](https://github.com/tldr-pages/tldr/pull/5232#issuecomment-773699671). Just to be sure this is perfectly clear: I very strongly oppose any intents to bypass the current processes and approval thresholds, unless absolutely crucial (e.g. for urgent security matters, or the most trivial of issues — such as, say, obvious typo fixes). I believe I speak for the community when I say this.

A community (especially a very permissive and collaborative one like ours) can only function when all its members can trust on each other to restrain themselves and to limit the use of their abilities to the kinds of actions that either have been encoded previously in general guidelines, or are the result of explicit consensus in specific discussions. We can't afford to write down every little nuance in explicit rules, lest they become so verbose and cumbersome than nobody will actually read them — so it's very important that we're able to rely on each other's judgment, and trust that they'll ask when in doubt rather than act unilaterally.

> I think we (maybe just you and the others, I'm pretty new here) should discuss it at some point.
> FYI—I did give it some thought before I opened this issue, because I know what you mean.

I'm glad you agree! I hope to be able to launch a more explicit discussion on this topic soon, when I get the chance to create a PR proposing the changes to the community role document that were recently discussed on Gitter (namely, the introduction of a maintainer emeritus role, and monotonicity of the role transitions).

**Comment by bl-ue** [comment]
>@bl-ue I must confess I am quite concerned about your insistence in this particular type of action. You've shown such interest more than once before, e.g. here. Just to be sure this is perfectly clear: I very strongly oppose any intents to bypass the current processes and approval thresholds, unless absolutely crucial (e.g. for urgent security matters, or the most trivial of issues — such as, say, obvious typo fixes). I believe I speak for the community when I say this.

@waldyrious I completely understand why you might be concerned!  As a matter of fact though, I've learned exactly when to use force-merge by watching @sbrl, and I'd never use it in any other, so you need not worry about that.  The reason I'm always talking about the force-merging it because that's the only difference between org owners and org members that I imediately notice.

I'd like to remove that concern you have @waldyrious because I would never force-merge unless for the reasons you've stated above, as I've only seen @sbrl do so for those same reasons. 👍🏻

**Comment by waldyrious** [comment]
That's great to hear, @bl-ue :) just to be clear, no particular person's words or actions should be taken as final, or a definitive distillation of our guidelines and culture — it is a permanent work in progress, and we all have to occasionally realign or simply check with each other to ensure we're all in the same page. Keep up the great work! 👍

**Comment by sbrl** [comment]
I generally force-merge in 2 specific situations:

1. For very trivial changes (e.g. typo corrections) to reduce notification load on others
2. For extremely urgent security matters (I have not yet had to do this in all the time I've been an owner, as far as I can remember)

The frequency at which I do (1) here is defined by how busy my notifications list is.

The other thing @bl-ue you get to be able to do as an org owner is manage roles, permissions, and settings for the entire tldr-pages organisation. And if you don't yet have admin privileges over the repos, you get that too.
