### ISSUE TITLE
tldr --render: clients or linter?

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5427]
It occurred to me this morning that the `--render` option should really be part of the linter, since rendering is really a development function and the linter is really a development tool.  It's also extra work for client developers, if they want to fully implement the spec, including all of the optional parts.

Any thoughts?

**Comment by sbrl** [comment]
The idea here is to see how a specific client renders a page to debug their implementation I think.

**Comment by gutjuri** [comment]
Closing this since `--render` is nowhere to be found in the [current client spec](https://github.com/tldr-pages/tldr/blob/3b645a018bafff8851ed5ec4c6b7846b0080d1a9/CLIENT-SPECIFICATION.md) and I thus assume that this option has been deprecated long ago. Reopen this issue if I'm wrong.

**Comment by kbdharun** [comment]
> Closing this since `--render` is nowhere to be found in the [current client spec](https://github.com/tldr-pages/tldr/blob/3b645a018bafff8851ed5ec4c6b7846b0080d1a9/CLIENT-SPECIFICATION.md) and I thus assume that this option has been deprecated long ago. Reopen this issue if I'm wrong.

Yeah, that's fine. This option is still widely used by our maintainers (including myself xD) and contributors for checking the page locally before creating a PR. (I am planning to add it to the PR template checklist as mentioned in the tracker issue in future)

`tldr --render` isn't included in the client specification as it might not be necessary for community clients with different objectives i.e. an extension, etc and different styles/implementations as mentioned by @sbrl. All our official clients have support for it. 

I think it would indeed be great to have this option added to `tldr-lint` so that we can just suggest installing it as a benchmark for rendering instead of depending on the client's rendering.

**Comment by sbrl** [comment]
Yeah, this issue wasn't really about whether `--render` should be added to the client spec or not.

Yep, you're exactly right there @kbdharun
