### ISSUE TITLE
Add organization member: @glenacota

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5769]
Hi, @glenacota! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks (reviewed/merged 22 
 PRs).
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by glenacota** [comment]
Wow! Super honoured! Unfortunately, I've had very little time lately, and I won't be as available as I'd like to be for another month or two. But I'll do my best to keep up and support!

**Comment by bl-ue** [comment]
No problem, @glenacota! I realize you're not very active, but I have noticed that whenever I ping you or request your review, you always respond. So while I wouldn't consider you that active, you're definitely still interested in the project, and I'd say a recognization of that should be made.

**Comment by waldyrious** [comment]
Hey @bl-ue and @glenacota — just to clarify, since this is a common point of confusion: a role transition is not primarily intended as recognition of work done, nor as an expectation of future work. It is essentially a convenience measure, allowing you to do things more easily (or do things that you weren't able to do before), but at the pace that works best _for you_.

It is actually good for everyone: the contributors get another pair of hands that can help out in situations where you currently can't; you get the ability to tackle more stuff without depending on other maintainers; and the other maintainers get another peer to help with another tasks (again, if _you_ decide to do them). A win/win/win situation!

Of course, the added visibility may lead more people to request feedback or assistance from you, but hopefully with multiple people in each maintainership tier, no single person should end up burdened by such role changes.

All that said, it's of course totally up to you to decide whether this change makes sense or not. We're happy to have you around either way!

<sub>ps - @bl-ue, maybe it's worth considering not pinging them as often if their time is short, as they say. One tends to feel obliged to offer feedback when it's directly requested of us, so the apparent availability may not correspond with the actual availability one would naturally settle into.</sub>

**Comment by Waples** [comment]
Shall I close this issue for now?

**Comment by waldyrious** [comment]
@Waples it would be preferable to let @glenacota respond. There's no hurry.
