### ISSUE TITLE
Idea: allow multiple `# command` lines to simplify the alias system

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#5832]
If we could add multiple `# command` lines like
```
# command
# command_alias1
# command_alias2

> command description
```
that would be a much simpler solution than creating a whole new page for an alias. Also, that would probably make it easier for users, since they could search for `pacman --files`, `pacman-files` or `pacman files` and always land on the same page. Maybe with a little note saying: `Redirected from ...`. Also that would make more complex cases like https://github.com/tldr-pages/tldr/pull/5823#discussion_r619831467 way easier, since there sometimes is no way the user could know how we named the page for a subcommand.

Regarding client support: There probably will be some issues, but we could test that for one page and look what the clients do. Hopefully they'll just ignore all, but the first one until they support the new syntax.

**Comment by peterbabic** [comment]
I would like to expand the idea a little bit. If instead of just specifying a command, also its directory (in this scenario it would be the command origin, or more psecifically, where the command came *from*), for instance
```
# linux/command
# linux/command_alias
# osx/command
```
This way, we would be able to get rid of the `common` folder and the problems associated with it, described in https://github.com/tldr-pages/tldr/issues/1966 
If the command would be available on multiple platforms, it would be simply aliased. Since the origin of the command can always be only one, it would be the specified by the location of the file itself.

But as with every complex system, paired with my lack of deeper understanding of this project, there would definitely be some gotchas. I am currently not sure how would client find the command - it would need to build some lookup table during installation / upgrading at the very least (I am on platform foo currently and all these commands are aliased here).

**Comment by marchersimon** [comment]
Nice idea, however I see two major problems with that:
* When changing the directory stucture, we can't just replace the old one because of backwards compatibility. Therefore we would have to maintain both structures simultaniously, which would add a lot of complexity.
* When you have a `command` page for `windows` and one for `osx` and `linux` and you dump it all into one directory, you have conflicting filenames. Solving that by changing filenames would completely changes the way tldr works.

When only adding multiple `# command` lines without changing any structure, we just have to make sure it doesn't break any major client (which shouldn't be too hard, since it's just a minor change).

**Comment by sbrl** [comment]
I'm not sure I understand what you're talking about here. Are you suggesting multiple titles to a page? Not sure it makes much sense to me.

**Comment by marchersimon** [comment]
For example, let's take `pio` and its alias `platformio`. I'm suggesting `pio.md` could look like this:
```
# pio
# platformio

> command description
...
```
That would be a much cleaner way to do aliasing instead of creating a new page for that alias.

**Comment by marchersimon** [comment]
Maybe we could keep it in mind if we ever get to redoing the whole structure. (Like tldr 2.0)

**Comment by marchersimon** [comment]
Should I close the issue?

**Comment by peterbabic** [comment]
@marchersimon I think maybe I was not clear enough - I definitely did not mean to "dump all the commands in the same folder", just to discontinue the `common` folder over time.

Additionally, maybe instead of the currently proposed syntax using multiple h1 tags, which in fact would not be understood well, something like [Front Matter](https://jekyllrb.com/docs/front-matter/) could be used, as it is generally not rendered.

**Comment by sbrl** [comment]
Issue #1082 has a good discussion on front matter @peterbabic

**Comment by marchersimon** [comment]
Closing, since my proposal doesn't seem realistic and doable
