### ISSUE TITLE
Add organization member: @aherst

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#6169]
Hi, @aherst! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks ().
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by CleanMachine1** [comment]
Well, what I would to say about this is, please start to help with the review process since as highlighted in the message above, it doesn't seem that you have done any, sorry if you have and it is a requirement in COMMUNITY-ROLES.md file

`Repository collaborators who regularly perform maintenance tasks should be added as organization member`

**Comment by CleanMachine1** [comment]
is:pr commenter:aherst as a search result, shows 1 PR maintenance.

Also please don't take this as a dig!

**Comment by aherst** [comment]
Noted. I thought the invitation was sent because I had met the criteria. I am trying to do more review of the linux/pages but I'm happy to stay at my current level for a while longer if I haven't been contributing enough.

**Comment by CleanMachine1** [comment]
I don't have any thing against it, you have done a lot of actual work in the form of new pages

**Comment by marchersimon** [comment]
@aherst becoming a member is mainly to be able to do maintenance tasks easier. For example you can now also review PRs in all tldr-pages repos. If you're interested in doing that then you're welcome as a member and if you'd like to mainly continue creating pages than I'm not sure being a member is necessary. (Even tough I don't have anything against it, since you're helping out a lot).

**Comment by CleanMachine1** [comment]
I'd say, wait at least a week, then review this again, it seems that you are contributing to at least 1 PR currently

**Comment by aherst** [comment]
OK. I don't need elevated privileges to keep on making the contribution I'm making. I'll revive this thread if I feel the situation has changed.
