### ISSUE TITLE
page request: grap, pic, tbl, eqn, troff, groff

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6348]
- [x] [grap](https://github.com/snorerot13/grap) → #6868
- [x] [pic](https://manned.org/pic) → #6868
- [x] [tbl](https://manned.org/tbl) → #6594
- [x] [eqn](https://manned.org/eqn) → #6868
- [x] [troff](https://manned.org/troff) → #6868
- [x] [groff](https://www.gnu.org/software/groff/manual/html_node/Groff-Options.html) → #6868

**Comment by CleanMachine1** [comment]
Where are you finding all of these missing pages?!?

Edited to show it as a checklist

**Comment by chrissxYT** [comment]
> Where are you finding all of these missing pages?!?

Some of them I actually wanted to look up (like `openscad` or `lipo`), sometimes I just look at all of my installed programs that are not in `tldr` ([`tldrgal missing`](https://github.com/chrissxYT/tldrgal/blob/1a28ae851d93d1fa3f3b177fd3beb549978e8196/tldrgal#L19)) and search for some that I recognize. And `grap`, `pic`, `eqn`, and `troff` are exceptions, because I saw `tbl` not being in `tldr` and then I tried the rest of 1970's pipe for making books. (watch any talk by Brian Kernighan, if you don't know them)

**Comment by git-em** [comment]
All of the requested commands are implemented. This should be closed.
