### ISSUE TITLE
Should we allow language specific `More information` links?

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6538]
While doing #6537, I noticed that some pages use more information links which used language tags.
For example `pages.fr/common/matlab.md` uses `https://fr.mathworks.com/help/matlab/`.
This is a problem when keeping all links synced, like I did in that PR. So should we allow language specific tags or just enforce the same link for every page?

**Comment by SethFalco** [comment]
The optimal solution would be to not specify any language. Websites should use [`Accept-Language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) to take users to the correct version of the site.

Unfortunately, many websites don't do this or aren't internationalized for other users at all. 

Plus many websites are stupid and automatically determine language using geolocation instead of `Accept-Language`. >:c
Even [MathWorks](https://www.mathworks.com/help/matlab/) does this and asks if I want Dutch, and I don't even know Dutch.

I think using language-agnostic links is an appropriate default, usually being the same as the English pages.

Based on my rant above, however, I think linking to resources available in the language of the page would improve the UX for users who browse non-English pages, or live in a country where they don't speak the language.

**Comment by marchersimon** [comment]
@CleanMachine1 @navarroaxel any other opinions?

**Comment by sbrl** [comment]
I agree with @SethFalco  here. If possible, a language-agnostic link is preferable - e.g. https://example.com/ instead of https://example.com/en/. If there's no possible alternative though, linking to language-specific pages is acceptable I think - but as you say the problem is then how to keep them all up to date....

I would suggest also that only translations that are a translation of the original resource would be appropriate. For example, if `foo` linked to the official documentation in English, then it would be inappropriate to link to a translated man page `foo` in French.

**Comment by CleanMachine1** [comment]
I also agree with SethFalco.

**Comment by marchersimon** [comment]
Great! Then I'll close this
