### ISSUE TITLE
Cannot find ss page using C client

### ISSUE THREAD

**Issue by viggy28** [tldr-pages/tldr#6607]
reference: https://man7.org/linux/man-pages/man8/ss.8.html

**Comment by navarroaxel** [comment]
Hi @viggy28, is this the page that you are looking for? https://github.com/tldr-pages/tldr/blob/main/pages/linux/ss.md

**Comment by viggy28** [comment]
thanks, @navarroaxel. Yeah, that's the page. Maybe something wrong with my version.

```
viggy28@localhost ~ % tldr ss
This page doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr
```

Any chance you know what the issue could be?

**Comment by navarroaxel** [comment]
@viggy28 Which client and version are you using? I think you should configure linux as platform to access linux pages.

**Comment by marchersimon** [comment]
It's the C client ([source](https://github.com/tldr-pages/tldr-c-client/blob/master/src/tldr.c#L178)).

This isn't a known bug, but the client isn't really maintained anyways. If you like to keep using the C client, I'm sure we can find a solution, but otherwise I can recommend the official [Python client](https://github.com/tldr-pages/tldr-python-client/), the official [Node.js client](https://github.com/tldr-pages/tldr-node-client) or the [C++ client](https://github.com/marchersimon/tldr-cpp/). (that one is from me)

**Comment by CleanMachine1** [comment]
I agree with @ marchersimon, I'd recommend the python client or C++ since they are the easiest to setup if you don't have Node.js installed.

**Comment by viggy28** [comment]
Thanks, all. I installed the Node.js client and it shows `ss`. 

I did look at @marchersimon C++ client. I am on macOS, didn't want to take the pain of building it. I would have tried if there is a brew package 👍

**Comment by CleanMachine1** [comment]
Well in that case, we'll close this issue.

**Comment by marchersimon** [comment]
> I did look at @marchersimon C++ client. I am on macOS, didn't want to take the pain of building it. I would have tried if there is a brew package

Too bad, but honestly I haven't tested it under OSX, so I don't even know if it would work.
