### ISSUE TITLE
alias: possibly inappropriate example commands

### ISSUE THREAD

**Issue by sanopy** [tldr-pages/tldr#7022]
When I run the creation of `rm` or `la` aliases shown in the [example commands of alias](https://github.com/tldr-pages/tldr/blob/main/pages/common/alias.md), I got the following result -- the alias name and command contain braces. Is it expected?

```
$ unalias -a
$ alias {{rm}}="{{rm -i}}"
$ alias {{la}}="{{ls -a}}"
$ alias
alias {{la}}='{{ls -a}}'
alias {{rm}}='{{rm -i}}'
```

I think the following example would be appropriate.

```
- Turn `rm` into an interactive command:

`alias rm="rm -i"`

- Create `la` as a shortcut for `ls -a`:

`alias la="ls -a"`
```

**Comment by CleanMachine1** [comment]
Are you using a client to view the pages?

The curly brackets are a feature of the clients so that they appear in a different color or format

{{word}} indicates that the word can be changed in the command.

If you aren't using a client I would recommend Marchersimon's c++ client or our official python client for ease of use.

**Comment by marchersimon** [comment]
@sanopy you could try opining an issue at [psibi/tldr-sh](https://github.com/psibi/tldr-hs). I'm going to close this, since this is a client-specific issue.
