### ISSUE TITLE
page request: pkgin

### ISSUE THREAD

**Issue by ghost** [tldr-pages/tldr#7077]
Documentation :  [NetBsd.org](https://www.netbsd.org/docs/pkgsrc/introduction.html#intro.platforms)
> - "There is a lot of software freely available for Unix-based systems, which is usually available in form of the source code. Before such software can be used, it needs to be configured to the local system, compiled and installed, and this is exactly what The NetBSD Packages Collection (pkgsrc) does. pkgsrc also has some basic commands to handle binary packages, so that not every user has to build the packages for himself, which is a time-costly task."

 --
> [Related To This Page on Tldr-Flutter client](https://github.com/Techno-Disaster/tldr-flutter/issues/12)

**Comment by Sadeeed** [comment]
id like to work on this, please assign

**Comment by Sadeeed** [comment]
I would like to work on this, please assign

**Comment by Sadeeed** [comment]
we might need to split this up into sub-pages, since pkgsrc itself isn't a single command
Here is a list of some potentially helpful resources
[pkgsrc.org](https://www.pkgsrc.org/)
[pkgsrc.se](https://pkgsrc.se)
[pkgin](https://pkgsrc.se/pkgtools/pkgin) - an apt like interface for installing pkgsrc packages
