### ISSUE TITLE
page request: nyxt

### ISSUE THREAD

**Issue by jtmlis** [tldr-pages/tldr#7408]
- include a link to a web page about the command
https://nyxt.atlas.engineer/
- if available, add an existing source of examples
https://github.com/atlas-engineer/nyxt

```
# nyxt

> keyboard-driven web browser
> Nyxt is a keyboard-driven web browser for power users.
> Inspired by Emacs and Vim it is extensible in Lisp.
> More information: <https://nyxt.atlas.engineer>.

- Print system information:
`nyxt --system-information`

- List all profiles:
`nyxt --list-data-profiles`

- Set init.lisp file path:
`nyxt --init {{path/to/file}}`

- Change the auto-config.lisp;
`nyxt --auto-config {{path/to/file}}`
```

**Comment by CleanMachine1** [comment]
Hi @jtmlis 

You do not need to submit a request like this for a new page. 

Simply add it via a PR! 

I assume you used an issue instead because of all of the other "page requests" but they are rather just undocumented commands which people request for others to make for TLDR. 

Hope this clears somethings up, and if you would like to add this via a PR feel free, or just mention if you want one of our maintainers to add it.
