### ISSUE TITLE
Commands that have different names among distros

### ISSUE THREAD

**Issue by blueskyson** [tldr-pages/tldr#7596]
For #7578. There exist some commands which have different name in different distros. For example:

| Distro | `lid` in `libuser` | `lid` in `id-utils` |
|--|--|--|
| Debian | rename to `libuser-lid` | `lid` |
| Redhat | `lid` | no package |
| Arch | `lid` (AUR) | rename to `lid-idutils` (AUR) |

Currently there is no document for dealing with such situation. I personally think that making a new template for the rare cases is not a good idea, because it only makes guideline more complex. Here are 2 solutions I thought about:

1. Create pages of different names with almost same examples.
2. Create alias page to deal with different names. (Maybe add some information about distro.)

Any idea?

**Comment by sbrl** [comment]
If I recall, there's was a command a while back where we had some serious trouble like this, but I can't remember what it was called, or the solution we put in place.

I'd advise giving the variants different names, and use a `see also` to reference them - assuming that the variants have different incompatible functionality and there is not a common denominator.

Should there be a common denominator though, it's perhaps better to document that instead and have 1 page instead of multiple.

**Comment by cyqsimon** [comment]
There are several ways we can view this issue:
1. From the binary perspective: same binary, but packaged under different names
2. From the distro perspective: different binaries having a naming conflict
3. From the "naive user" perspective: TLDR is misleading me

What I'm trying to say is that the solution is not straight-forward at all. It's not easy to implement a system that's both "clean" from a code perspective, and make it easy and convenient to use from a user perspective, not to mention the effort required to update the protocol/format/standard and have various clients implement them.

**Comment by cyqsimon** [comment]
A potential solution I'm thinking of is "the Wikipedia solution". I.e. Simply have a disambiguation page as the main page landing page for the name in question, which lists `tldr` commands to show the actual pages for the respective binaries. So that would look something like this, using `lid` as an example:

### `lid.md`
```markdown
# lid (disambiguation)

> libuser-lid: Display a user's groups or a group's users.

`tldr libuser-lid`

- id-utils-lid: Query ID database and report results.

`tldr id-utils-lid`
```

### `libuser-lid.md`
```markdown
# libuser-lid

> Display a user's groups or a group's users.
> Alias on Debian-based distros: `libuser-lid`
> More information: <https://manned.org/lid.8>.

- Show a user's groups (primary and secondary):

`sudo lid {{user}}`

- Show a group's users:

`sudo lid --group {{group}}`
```

### `id-utils-lid.md`
```markdown
# id-utils-lid

> Query ID database and report results.
> Alias on Arch-based distros: `lid-idutils`
> More information: <TODO>.

- Examples here

`echo todo`
```

This solution has the advantage of not requiring clients to be updated. Old TLDR clients can simply treat the disambiguation page as any other regular page, and it only requires one extra command from the user, which I don't think is that big of a deal.

Of course, clients can be updated to simply match on the string `(disambiguation)` (or any other string, as long as we standardise it) in the title line, and display a selection interface to the user. But that would be an optional feature that's up to the client to implement.

**Comment by blueskyson** [comment]
@cyqsimon Your solution is great.

**Comment by cyqsimon** [comment]
A few checklist items, if the Wikipedia solution is to be adopted:

- [ ] Formalise the marker string for a disambiguation page
  - Current proposed: `(disambiguation)`
  - Or should we considering using a special symbol? (Probably not but it's worth asking)
- [ ] Formalise the package-binary delimiter
  - Current proposed: `-` (e.g. `libuser-lid.md`)
  - Should we perhaps consider using `_` instead? I'm suggesting this because some binaries contain `-`(s) in their names
- [ ] Update documentation regarding policy and recommendation for client programs

I'll add more if they come to mind.

**Comment by blueskyson** [comment]
@cyqsimon I don't really know what is "marker string". I would prefer to use `lid.md` as main page and write the three pages as the following:

**lid.md**
```
# lid

> Display a user's groups or a group's users.
> This command may be named as `libuser-lid` or `lid-idutils` among distros.
> descriptions...

- examples...
```

**libuser-lid.md**
```
# libuser-lid

> This command is an alias of `lid`.

- View documentation for the original command:

`tldr lid`
```

**id-utils-lid.md**
```
# id-utils-lid

> This command is an alias of `lid`.

- View documentation for the original command:

`tldr lid`
```

It won't change the tldr's path structure by this way.

**Comment by cyqsimon** [comment]
No no, you're completely misunderstanding the relationship between `libuser-lid` and `id-utils-lid`. They are ***two completely different binaries*** in ***two completely unrelated packages***, ***NOT*** simple aliases. I would encourage you to get several VMs (Arch, Fedora, Debian) and play around a bit.

As of why I suggest we have a "disambiguation string", this is so that from a client perspective it's easy to differentiate a normal page from a disambiguation (or you may call it "redirection") page. The client program may be modified to handle such pages differently, so you might get something like this:
```
$ tldr lid
  Two packages provide the `lid` binary: `libuser` and `id-utils`.
    1. libuser-lid: Display a user's groups or a group's users.
    2. id-utils-lid: Query ID database and report results.
  Please select one by its id:
> 1
  Display a user's groups or a group's users.
  Alias on Debian-based distros: `libuser-lid`
  More information: <https://manned.org/lid.8>.
  Show a user's groups (primary and secondary):
      sudo lid user
  Show a group's users:
      sudo lid --group group
```

**Comment by cyqsimon** [comment]
What I am implicitly saying, is that the markdown file name should be **a unique identifier** for a binary, rather than a 1-to-1 match for its actual name on a particular distro. Much like how on Wikipedia, https://en.wikipedia.org/wiki/Python points to the disambiguation page, while python (as in snake) resides in https://en.wikipedia.org/wiki/Pythonidae, and Python (as in language) resides in https://en.wikipedia.org/wiki/Python_(programming_language).

**Comment by blueskyson** [comment]
Oh, I understand the concept of Wikipedia solution. Then you can just implement it in your PR. You may explain this with the python example to other maintainers since this is a new idea of tldr.

**Comment by cyqsimon** [comment]
Doesn't tldr have a formal RFC-like process for big changes like this? I'm happy to implement my PR this way of course, but I would like to see more discussion before merging my changes. After all, this would set a precedence and if so, it would be nice if we first formalise it as a standard.

**Comment by EmilySeville7cfg** [comment]
> Create alias page to deal with different names. (Maybe add some information about distro.)

Creating alias is the right option just in case two commands are identical in their behavior except their name. :)

**Comment by Waples** [comment]
Sup other mods? Are you still working on this or can we clean this up?

**Comment by sbrl** [comment]
Hey there, @sebastiaanspeck, @Waples! It looks like this issue was created more as a discussion point about what to do in a specific case. It seems like a decision was reached by @MasterOdin, so this is really just blocking on #7578.

I would agree with @MasterOdin in that a `See also` is the best solution in this specific case.

**Comment by kbdharun** [comment]
> Any update on this? So we can close/merge #7578

We can follow the same approach as `just` page I guess.

**Comment by sbrl** [comment]
@sebastiaanspeck I've commented on the PR. Thanks for the reminder, I think we've all been avoiding the messiness of this specific issue.

I wouldn't rush this one, but thanks again for the reminder.

**Comment by sbrl** [comment]
Now that #7578 is closed, I believe we can close this one too.

To the best of my knowledge, the solution implemented was that of a disambiguation page. Consider the command `lid` from the id-utils package, and `lid` from the package libuser.

The solution here is to document to consider the id-utils version of `lid` as the 'main' version and document it under `lid.md`, and document the libuser version under `libuser-lid`.

Then, we added a `See also` to `lid` mentioning the libuser version that's documented under i.e. `libuser-lid`.

Should this situation be encountered again, this is the solution that should be considered. Should none of the clashing commands be significantly more popular than the other, a disambiguation page would be appropriate.

If this explanation is incorrect, I hereby give permission for maintainers to edit this comment to keep the history of this issue tidy, so long as you leave a changelog behind.

**Comment by cyqsimon** [comment]
@sbrl I've made quite a few amendments and clarifications. Also I've reduced the scope of applicability because I'd rather this solution be narrow and well-defined than broad and loose. Please take a look, thanks.
