### ISSUE TITLE
Move chat to Telegram

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7902]
What about moving Gitter chat to Telegram? I think it's better then Gitter. ;)

**Comment by pixelcmtd** [comment]
tf no

Seriously though, what are the advantages? I only know disadvantages.

**Comment by CleanMachine1** [comment]
I can't see any positives here either.

We have everything setup for Gitter, most of our maintainers are in the Gitter.
I would imagine that the conflict from switching would mean that some just wouldn't switch.
Also, everyone here has a Github account _(obviously)_ which means they can make a Gitter account in amount a second.

Gitter is made for Repos, due to its integration, telegram is not.

Have you got any advantages with using Telegram @EmilySeville7cfg

**Comment by EmilySeville7cfg** [comment]
For me Telegram is faster and less buggy then Gitter. For instance when I read messages in Gitter they are often remain unread until I do this several times. But I agree that GitHub integration is good enough in Gitter (issue hints, for instance, notifications, etc.). For Telegram we can use Integromat for instance to make GitHub integration (or any it's alternative).

It's a pity that there is no way to view attachments in Gitter like in Telegram.

**Comment by CleanMachine1** [comment]
I find that to remove the notification banner, you need to click it for it to take effect that you have "read" the notification.

And for attachments, other then the occasional picture being sent, mostly links are being sent.

Lets get some more opinions

**Comment by sbrl** [comment]
I don't currently use Telegram myself. Gitter has quite deep integration with GitHub, which I find very helpful.

So I'd prefer to keep it on Gitter.

If you don't like the Gitter interface, you can always join via a matrix client instead? Gitter is now backed by matrix - I think a number of people join via a matrix client already.
