### ISSUE TITLE
tldr --create

### ISSUE THREAD

**Issue by sarnobat** [tldr-pages/tldr#7968]
Is there a pure-cli way to create an entry for an undocumented command?

I love tldr and would like to fill in the gaps but going to github and providing a pull request is enough to discourage me. I just want to add `--create` to a failed lookup command, paste something into vim, and leave all the review etc. to some automated process (to be rejected or approved as the owners see fit).

Thanks for such a useful tool. On another note, I run tldr --random on my 2nd screen as an educational screensaver, it's that useful :) I'd also like to say the maintainers here are the friendliest of any on the web.

**Comment by pixelcmtd** [comment]
Yes, there is, it's called [tldrgal](https://github.com/pixelcmtd/tldrgal), but it's a bunch of hacked up and unmaintainable code.

Getting it into the tldr command is actually the wrong way imo, because with how many clients there are and how complicated implementing such an option is, we would need months to come up with a spec for what it should actually do and until we get 90% of the install base of clients to support it, it would take like 5 years.

I'd instead suggest something like making a bunch of scripts in this repo or writing an official tool for contributing.

**Comment by CleanMachine1** [comment]
I'd like to add this short piece of code I made which I have been occasionally working on.
It helps in creating the pages by trying to match syntax. It is nothing fancy, merely tries to remove linting errors and dumbs down the process to just be a fill the gap.
[Check it out if you don't mind](https://github.com/CleanMachine1/tldr-page-creator)

**Comment by CleanMachine1** [comment]
> I'd also like to say the maintainers here are the friendliest of any on the web.

Thanks!

**Comment by sarnobat** [comment]
Thanks for the responses. That's enough info for me to pursue this a little further, so I'm closing. Feel free to reopen if you wish to repurpose this ticket.
