### ISSUE TITLE
Update wiki link

### ISSUE THREAD

**Issue by finzzz** [tldr-pages/tldr#7974]
I want to update repo URL in https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients

This line here
```
@finzzz 	tldr.finzzz.net 	Available online at https://tldr.finzzz.net/
```

Can you point the source code to https://github.com/finzzz/tldr ?

Thanks!

**Comment by CleanMachine1** [comment]
I have never dealt with the WIKI we have here, however all of the other clients in the web category all point to the implementation rather than the source code.

It may be better to add a link to the source code on the website maybe?

Lets get the opinion of others before I dismiss this request, since I am just one reviewer!

**Comment by pixelcmtd** [comment]
@CleanMachine1 all of the links entitled `Source code` point to the repo of the client.

@finzzz I just changed it.

**Comment by CleanMachine1** [comment]
:facepalm: didn't see that.
