### ISSUE TITLE
FreeBSD / OpenBSD section(s) proposal.

### ISSUE THREAD

**Issue by Cvetomird91** [tldr-pages/tldr#816]
I am opening this issue in order to discuss the probability of adding a section for any of those influential Unix-based operating systems.

I see that there are SunOS and OS X sections besides the Linux one. FreeBSD had a huge impact on OS X, but both are separate systems and are quite different. OS X is based on the Darwin OS's Mach kernel which is separate from the FreeBSD one, although Apple's version of it includes some FreeBSD components.

**Comment by Leandros** [comment]
(y)

**Comment by igorshubovych** [comment]
Sorry for a n00b question.
Can you please mention one or a few differences in command syntax for OSX in BSD, so we can better understand the need for this?

**Comment by Cvetomird91** [comment]
For example, MacOS and FreeBSD have different firewalls. MacOS's packet filter is called socketfilterfw and FreeBSD's packet filter is ipfw. Also, they use different packaging systems. FreeBSD uses the pkg utility to download pre-built packages.

**Comment by waldyrious** [comment]
I wonder if we should implement some sort of fallback mechanism. Right now every platform falls back to common, but we should be able to only provide osx-specific pages that differ from freebsd (or vice-versa) and let the remaining pages fall back to the other platform, before going to common. Paging @rprieto.

But don't let this suggestion halt progress in the quick-and-dirty solution of just duplicating the pages for now -- perfect is the enemy of the good :)

**Comment by Cvetomird91** [comment]
Good idea, waldyrious.

However, I'm not imply

However, I'm not implying on duplicating pages. I am proposing sections where FreeBSD or OpenBSD specific commands can be added.

**Comment by FlyingJester** [comment]
This is a good idea. Many commands in OpenBSD and FreeBSD do behave differently than their Linux and OS X counterparts. Even very common ones, like tar and mount. As an example, the current tar page is not as useful for OpenBSD, since it demonstrates a couple GNU extensions not present on OpenBSD.

**Comment by dylanrees** [comment]
I agree with this.  One of the first additions could be the OpenBSD sudo alternative:

http://man.openbsd.org/OpenBSD-current/man1/doas.1

**Comment by zdroid** [comment]
bump

My suggestion is to name the supposed directory `pages/bsd/` if there's still interest for it.

**Comment by agnivade** [comment]
There is still the question of fallback. I think we want to fallback to osx-specific pages first, and then go to common. But the logic that we have now is to directly fallback to common.

Also, what platform does BSD resolve to now ? Linux or OSX ? If it is linux, then not implementing the osx-specific fallback would still be fine.

In any case, this also needs to be added to the node client first as a new platform.

**Comment by zdroid** [comment]
As far as I know, it's more OS X than Linux, but it's more an issue of fallback which was mentioned in some other issue.

**Comment by sbrl** [comment]
I wasn't aware of this issue before. As far as I was aware it was `os_name` first, which then falls back to `common`. The page resolution logic has been standardised in the client spec [here](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#page-resolution).

We also have been putting commands present in moret han 1 OS in `common`, rather than commands available on _all_ OSes in `common` with copies in the platform-specific folders, as we had before.

I'm not quite sure what the fallback issue is here. It sounds like a separate issue - is it worth opening a new issue for it?

I'd also suggest that a `bsd` platform would be fine - we'd just need someone to contribute the first page :-)

Also according to the client spec ([ref](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#directory-structure)), adding additional platforms shouldn't break clients. This was indeed the case with the `windows` platform that was added semi-recently. So I don't think we've got much to worry about there.

**Comment by zdroid** [comment]
Then I guess this could be closed by adding a note in readme or contributing guidelines. We need to note it somehow that BSD is supported, we're just waiting for someone to write a page for some of its commands. :smile:

**Comment by sbrl** [comment]
Perhaps @zdroid, but that seems to me like more work that just contributing the first page lol :P

**Comment by zdroid** [comment]
That's surpisingly true. :P 

I just don't know which command is specifically BSD's, but there is surely one. [`pico`](https://www.computerhope.com/unix/upico.htm) is a candidate since its fork `nano` replaced it on Linux long time ago.
