### ISSUE TITLE
improve `tldr tldr` with information how tldr should be updated

### ISSUE THREAD

**Issue by matkoniecz** [tldr-pages/tldr#824]
I wanted to update tldr so I checked `tldr tldr` ( http://www.ostera.io/tldr.jsx/#/tldr?_k=fk6knt )

>    Update the local cache of tldr pages:
> 
> tldr --update

I tried `tldr --update` what resulted in 

> usage: tldr [-h] [-o {linux,osx,sunos}] command [command ...]
> tldr: error: the following arguments are required: command

So I tried `tldr -o linux --update` what also resulted in

> usage: tldr [-h] [-o {linux,osx,sunos}] command [command ...]
> tldr: error: the following arguments are required: command

**Comment by waldyrious** [comment]
@matkoniecz thanks for raising this issue. This is something we've considered in the past but haven't made a decision yet. The documentation for this option was added in #744 and in that PR we discussed making the contents of the tldr tldr output a formal requirement for clients to be featured in our README, but we didn't reach consensus. This issue is probably a good place to finalize that discussion and move forward.

May I ask what client you're using? python, node?...

**Comment by matkoniecz** [comment]
python (I see tldr in `pip list` )

**Comment by waldyrious** [comment]
Back-reference: #744

**Comment by daylightbrightledlight** [comment]
So does this mean that this issue can be closed? I think we can close this issue now.

**Comment by sbrl** [comment]
Hrm, I'm not sure @daylightbrightledlight. The thing is that although each client is has the same basic similarities, they also all have their own flags and options. I suspect that this is a case of that. I wonder if there's a formal spec for 'official' tldr clients? Perhaps @waldyrious or @agnivade would know.

**Comment by agnivade** [comment]
We do have a minimal page here - https://github.com/tldr-pages/tldr/wiki/Minimum-specifications-for-TLDR-command-line-clients

Some more thoughts here - https://github.com/tldr-pages/tldr/issues/1065

But yes, I agree this is a client specific thing. I would say we should remove the `--update` flag as it is not there in python client.

**Comment by sbrl** [comment]
Ah, ok @agnivade. I've opened #2272, which removes the --update flag.
