### ISSUE TITLE
[FEATURE REQUEST] Auto complete functionality

### ISSUE THREAD

**Issue by parinck** [tldr-pages/tldr#874]
would be of immense help if we can add autocomplete functionality.

**Comment by ostera** [comment]
@patrick, the `node` client already has autocompletion both for [bash](https://github.com/tldr-pages/tldr-node-client/pull/97) and for [zsh](https://github.com/tldr-pages/tldr-node-client/pull/90).

It should be trivial to implement for any other client that complies with the `tldr -l -1` or `tldr -a1` APIs.

Perhaps these should be in a separate repository and included as git submodules for the clients so they can all share them? 

I'll start a new Issue for this topic if anyone :+1: for discussion, otherwise this one can be closed.
