### ISSUE TITLE
On Streamlining the Issues and PR Feedback Process (And some more)

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr#980]
Some ideas that would make this nicer:

## Travis-CI will post and update a checklist with the errors to be fixed
While most people are happy with checking travis logs, it's a step less for us to just look for a message like the one below when a Travis build has failed, and make sure it's been all checked.

> Hi! We found some errors in your pages. Please attend to them soon so we can take a look at your page!
> - [ ] pages/linux/strace.md:21: TLDR005 Example descriptions should end in a colon
> - [ ] pages/linux/strace.md:21: TLDR006 Command name and description should be separated by an empty line

## Auto-post a Message to new Issues
It shouldn't take too long to post a welcome message not unlike below to new command proposals:

>Thanks for reporting! Feel free to [send a PR](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#submitting-a-pull-request) to propose this page — if in doubt, take a look at [CONTRIBUTING.md]
(https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) for some guidelines, and let us know if you need any help :)

## Ping Contributors for certain commands
Make a list of commands some of the contributors are proficient with and ping them on the corresponding PR's touching those files

```yaml
contributors:
  waldyrious:
    - emacs
    - find
    - ls
  ostera:
    - vim
    - lsof
  igorshubovych:
    - npm
    - find
```

## Communication Channel
While gitter is a good place that comes _for free_ to talk about things, it's both a very heavy app and not a very popular alternative to IRC/Slack channels; or perhaps it's in the nature of our community to be slightly more passive.

If we decided to take our talks elsewhere, i.e, by deploying a [Slackin'](http://rauchg.com/slackin/) instance on Heroku which is free and gets anyone access to a Slack channel, perhaps we'd be able to communicate better with each other? It's a bit hard sometimes to get a hold of us 😝 

## Analytics and Understanding what People Look For
As of lately, I've been tracking more detailed analytics about command searches, and I could provide a list of not-found commands.

Travis could pull it down from Mixpanel, and update an Issue here with a checklist to facilitate commands that people are looking for but can't find.

-------

This isn't too big of a deal, but it'll save us quite some time in the long run :)

Would love to hear your thoughts!

**Comment by agnivade** [comment]
> Travis-CI will post and update a checklist with the errors to be fixed

This is an absolute no-brainer. Posting a message with a checklist is immensely helpful to beginners, who might be off-put to look into travis logs when their PR fails. Lets get the ball rolling on this one.

> Auto-post a Message to new Issues

Nice idea, but I am wondering how are we going to distinguish between issues which are about commands being absent and issues which are about something else ?

> Ping Contributors for certain commands

This is going to be indispensable as we grow bigger. IMO maintaining a list of commands with their contributors will be too much to keep on updating. Instead, I propose, something like this [mention-bot](https://github.com/facebook/mention-bot). Its pretty neat, and I have seen this being used in a lot of projects.

> Analytics and Understanding what People Look For

I am especially interested in this. Would love to add/update pages which people actually look for, rather than what I think will be good. Can we have a wiki page on this ? And have Travis or something else update that regularly ? Maybe top 10 searched but not-found pages, and top 10 searched pages which exist. Then I can take a command one by one and start adding them. I am proposing a wiki page rather than an issue because I feel issues are more like an action item about a specific thing. This feels like a passive metadata sort of thing - from where issues can be created and worked on.

**Comment by waldyrious** [comment]
Absolutely love the spirit of this proposal, and agree with pretty much everything in the original post. Apart from @agnivade's comments, which I subscribe (especially regarding mention-bot which sounds like an awesome idea!), I'd also add that one thing we clearly need is a way to handle the natural flow of maintainers: people's availability varies over time, so a hand-picked, small maintainer team won't be resilient in the long-run. I suggest something more permeable, inspired in the model used by Wikipedia: after a contributor has, say, 3 PRs merged, they should automatically get commit rights, and after X more commits they should be made part of the tldr-pages organization. If this could be implemented automatically, even better. That way the project is able to scale naturally, and avoid the stagnation that often plagues to such endeavors once the original team loses steam.

**Comment by ostera** [comment]
On the note about communication channels, you can [Join the Slack channel here](https://tldr-pages.herokuapp.com/)

**Comment by ostera** [comment]
Closing as this bigger goal has been split into smaller, digestible chunks.
