### ISSUE TITLE
md5sum: echo example has newline

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#9910]
Just so people are aware: example `echo "{{text}}" | md5sum` will calculate the md5 of `text\n`. For without newline use `printf` or `echo -n`. 

I'm not sure we even need such an example since it could apply to all checksum commands, but it could be useful.

**Comment by osalbahr** [comment]
It’s interesting that you mentioned printf. If we were to include such example, I am more in favor for a printf example, because apparently `echo -e` might not always work as expected https://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo.

I don’t think we need to have such example, though. If one were to use md5sum in conjunction with echo, they should know how echo works (either from the man page or the tldr) and that md5sum just reads from its `stdin`. But I guess it doesn’t hurt if the list of commands is less than 8.
